import type { ChakraData, ChakraName } from '@/types/cosmic';

export const CHAKRAS_LIST: ChakraData[] = [
  {
    name: "root",
    title: "Root Chakra",
    color: "#FF0000",
    element: "Earth",
    location: "Base of spine",
    strengths: [
      "Strong sense of security and stability",
      "Feeling grounded and present in your body",
      "Ability to provide for your basic needs",
      "Healthy connection to family and community",
    ],
    weaknesses: [
      "Chronic worry about money or survival",
      "Feeling ungrounded, anxious, or disconnected",
      "Fear of change and resistance to letting go",
      "Physical fatigue and lack of vitality",
    ],
    balanceSuggestions: [
      "Walk barefoot on grass or earth",
      "Practice grounding meditation visualizing red light at the spine base",
      "Eat root vegetables and red foods",
      "Establish consistent daily routines",
      "Spend time in nature regularly",
    ],
    meditationAdvice: "Visualize a spinning red wheel of light at the base of your spine. Imagine roots growing from your feet deep into the Earth, anchoring you to its core. Breathe deeply and feel the stability of the ground supporting you completely.",
    crystals: ["Red Jasper", "Black Tourmaline", "Hematite", "Smoky Quartz", "Garnet"],
    affirmation: "I am safe, secure, and deeply rooted in the Earth. I trust life to support me.",
  },
  {
    name: "sacral",
    title: "Sacral Chakra",
    color: "#FF7A00",
    element: "Water",
    location: "Lower abdomen",
    strengths: [
      "Healthy expression of emotions and creativity",
      "Comfortable with pleasure and sensuality",
      "Passionate approach to life and relationships",
      "Ability to flow with change and embrace new experiences",
    ],
    weaknesses: [
      "Emotional instability and mood swings",
      "Creative blocks and lack of inspiration",
      "Guilt or shame around pleasure and sexuality",
      "Difficulty with intimacy and vulnerability",
    ],
    balanceSuggestions: [
      "Engage in creative activities — painting, dancing, writing",
      "Take warm baths or swim in natural water",
      "Wear orange clothing or surround yourself with orange",
      "Practice hip-opening yoga poses",
      "Journal about your emotions without judgment",
    ],
    meditationAdvice: "Visualize a warm orange sphere of light glowing in your lower abdomen. Allow it to swirl and flow like water, releasing any blocks or inhibitions. Feel your creativity and passion awakening with each breath.",
    crystals: ["Carnelian", "Orange Calcite", "Moonstone", "Sunstone", "Peach Aventurine"],
    affirmation: "I honor my emotions, my creativity, and my sensuality. I allow pleasure and passion to flow freely through my life.",
  },
  {
    name: "solar-plexus",
    title: "Solar Plexus Chakra",
    color: "#FFD700",
    element: "Fire",
    location: "Upper abdomen",
    strengths: [
      "Strong sense of personal power and confidence",
      "Ability to set healthy boundaries",
      "Self-discipline and motivation to achieve goals",
      "Healthy self-esteem and self-worth",
    ],
    weaknesses: [
      "Low self-esteem and lack of confidence",
      "Difficulty saying no or asserting boundaries",
      "Need for control and domination",
      "Indecisiveness and lack of direction",
    ],
    balanceSuggestions: [
      "Practice assertiveness in small daily situations",
      "Engage in core-strengthening physical exercise",
      "Spend time in the sun absorbing its energy",
      "Set clear personal boundaries and honor them",
      "Use empowering affirmations throughout the day",
    ],
    meditationAdvice: "Visualize a brilliant golden-yellow sun radiating from your solar plexus. Feel its warmth spreading power and confidence through your entire being. With each exhale, release doubt and insecurity. With each inhale, draw in personal power.",
    crystals: ["Citrine", "Yellow Tiger's Eye", "Amber", "Golden Topaz", "Pyrite"],
    affirmation: "I am powerful, confident, and worthy. I stand in my truth and claim my personal authority.",
  },
  {
    name: "heart",
    title: "Heart Chakra",
    color: "#00FF00",
    element: "Air",
    location: "Center of chest",
    strengths: [
      "Capacity for unconditional love and compassion",
      "Healthy, balanced relationships",
      "Ability to forgive and let go of grudges",
      "Deep empathy and connection to others",
    ],
    weaknesses: [
      "Difficulty giving or receiving love",
      "Grief, heartache, and emotional wounds",
      "Codependency and losing self in relationships",
      "Inability to forgive or trust after betrayal",
    ],
    balanceSuggestions: [
      "Practice loving-kindness meditation",
      "Spend time with people and pets you love",
      "Volunteer or perform acts of kindness",
      "Wear green or pink clothing",
      "Practice forgiveness — starting with yourself",
    ],
    meditationAdvice: "Visualize a radiant emerald green light swirling in the center of your chest. Feel it opening like a flower, expanding with each breath. Send love from your heart to yourself, to loved ones, and to all beings. Feel the interconnectedness of all life.",
    crystals: ["Rose Quartz", "Green Aventurine", "Emerald", "Jade", "Malachite"],
    affirmation: "I am worthy of love, and I give and receive love freely. My heart is open, healing, and full of compassion.",
  },
  {
    name: "throat",
    title: "Throat Chakra",
    color: "#00BFFF",
    element: "Ether",
    location: "Throat",
    strengths: [
      "Clear, authentic self-expression",
      "Ability to speak your truth with kindness",
      "Good listener and effective communicator",
      "Creative expression through voice and art",
    ],
    weaknesses: [
      "Fear of speaking up or being heard",
      "Difficulty expressing true feelings",
      "Chronic sore throat or neck tension",
      "Tendency to gossip or speak without thinking",
    ],
    balanceSuggestions: [
      "Practice honest communication in safe settings",
      "Sing, chant, or hum daily",
      "Write in a journal to express unspoken thoughts",
      "Wear blue clothing or accessories near the throat",
      "Sip warm tea and keep the throat hydrated",
    ],
    meditationAdvice: "Visualize a vibrant blue lotus spinning at your throat. With each breath, feel the energy clearing, allowing your authentic voice to rise. Speak your truth silently or aloud — let the words flow without judgment or fear.",
    crystals: ["Lapis Lazuli", "Blue Lace Agate", "Aquamarine", "Sodalite", "Turquoise"],
    affirmation: "I speak my truth with clarity, confidence, and compassion. My voice matters and I am heard.",
  },
  {
    name: "third-eye",
    title: "Third Eye Chakra",
    color: "#4B0082",
    element: "Light",
    location: "Forehead between eyebrows",
    strengths: [
      "Strong intuition and inner knowing",
      "Ability to see beyond the surface",
      "Imagination and creative vision",
      "Wisdom and clarity of thought",
    ],
    weaknesses: [
      "Difficulty trusting intuition",
      "Overthinking and mental confusion",
      "Closed-mindedness and rigid beliefs",
      "Headaches or eye strain from mental pressure",
    ],
    balanceSuggestions: [
      "Practice regular meditation and mindfulness",
      "Keep a dream journal",
      "Limit screen time and rest your eyes",
      "Spend time stargazing or in dim light",
      "Trust your gut feelings and act on them",
    ],
    meditationAdvice: "Visualize a deep indigo light glowing between your eyebrows. See it as a screen receiving wisdom from the universe. Allow images, insights, and knowing to arise without forcing them. Trust what you see and feel.",
    crystals: ["Amethyst", "Lapis Lazuli", "Sodalite", "Fluorite", "Purple Labradorite"],
    affirmation: "I trust my inner wisdom and see clearly with my mind's eye. My intuition guides me perfectly.",
  },
  {
    name: "crown",
    title: "Crown Chakra",
    color: "#9400D3",
    element: "Divine Consciousness",
    location: "Top of the head",
    strengths: [
      "Deep spiritual connection and awareness",
      "Sense of unity with all existence",
      "Access to higher wisdom and guidance",
      "Inner peace beyond circumstances",
    ],
    weaknesses: [
      "Feeling spiritually disconnected or empty",
      "Cynicism and lack of meaning",
      "Attachment to material reality only",
      "Headaches or dizziness from spiritual pressure",
    ],
    balanceSuggestions: [
      "Practice silent meditation and stillness",
      "Study spiritual texts and philosophies",
      "Spend time in silence and solitude",
      "Connect with a spiritual community",
      "Practice gratitude for the mystery of existence",
    ],
    meditationAdvice: "Visualize a brilliant violet-white light at the crown of your head, opening like a thousand-petaled lotus. Feel divine light streaming from the cosmos into your being, connecting you to all that is. Rest in the awareness that you are one with the infinite.",
    crystals: ["Clear Quartz", "Amethyst", "Selenite", "Lepidolite", "White Howlite"],
    affirmation: "I am one with the universe. I am open to divine guidance, wisdom, and infinite consciousness.",
  },
];

export const CHAKRA_BY_NAME: Record<ChakraName, ChakraData> =
  Object.fromEntries(CHAKRAS_LIST.map((c) => [c.name, c])) as Record<ChakraName, ChakraData>;

export const CHAKRAS: Record<ChakraName, ChakraData> = CHAKRA_BY_NAME;
