import type { ChakraData, ChakraName } from '@/types/cosmic';

export const CHAKRAS: Record<ChakraName, ChakraData> = {
  root: {
    name: "root",
    title: "Root Chakra",
    color: "#e11d48",
    element: "Earth",
    location: "Base of spine",
    strengths: ["Feeling grounded and secure", "Sense of belonging", "Basic trust in life", "Stability and safety"],
    weaknesses: ["Anxiety and fear", "Feeling disconnected", "Financial insecurity", "Survival mode thinking"],
    balanceSuggestions: [
      "Walk barefoot on grass or earth",
      "Eat root vegetables and red foods",
      "Practice grounding meditation",
      "Establish stable daily routines",
      "Connect with nature regularly",
    ],
    meditationAdvice: "Visualize a glowing red light at the base of your spine. Imagine roots growing from your body deep into the earth, anchoring you with stability and strength.",
    crystals: ["Red Jasper", "Hematite", "Smoky Quartz", "Black Tourmaline", "Garnet"],
    affirmation: "I am safe, secure, and deeply grounded. I trust life to support me.",
  },
  sacral: {
    name: "sacral",
    title: "Sacral Chakra",
    color: "#f97316",
    element: "Water",
    location: "Lower abdomen",
    strengths: ["Healthy emotions", "Creative expression", "Sexual vitality", "Passion for life"],
    weaknesses: ["Emotional instability", "Creative blocks", "Guilt or shame", "Emotional numbness"],
    balanceSuggestions: [
      "Engage in creative activities",
      "Dance or move your body freely",
      "Spend time near water",
      "Honor your emotions without judgment",
      "Practice healthy pleasure and self-care",
    ],
    meditationAdvice: "Visualize a warm orange glow in your lower abdomen. Feel the flow of creative energy and let your hips gently sway with the rhythm of life.",
    crystals: ["Carnelian", "Orange Calcite", "Moonstone", "Sunstone", "Peach Aventurine"],
    affirmation: "I embrace my creativity, my emotions, and my passion for life.",
  },
  "solar-plexus": {
    name: "solar-plexus",
    title: "Solar Plexus Chakra",
    color: "#eab308",
    element: "Fire",
    location: "Upper abdomen",
    strengths: ["Personal power", "Healthy self-esteem", "Confidence", "Willpower and determination"],
    weaknesses: ["Low self-worth", "Feeling powerless", "Perfectionism", "Control issues"],
    balanceSuggestions: [
      "Practice confident posture",
      "Set and maintain boundaries",
      "Celebrate small achievements",
      "Engage in empowering activities",
      "Use affirmations for self-worth",
    ],
    meditationAdvice: "Visualize a brilliant golden sun in your solar plexus. Feel its warmth radiating confidence and personal power throughout your entire being.",
    crystals: ["Citrine", "Yellow Jasper", "Tiger's Eye", "Amber", "Pyrite"],
    affirmation: "I am powerful, confident, and worthy of all the good that life offers.",
  },
  heart: {
    name: "heart",
    title: "Heart Chakra",
    color: "#22c55e",
    element: "Air",
    location: "Center of chest",
    strengths: ["Unconditional love", "Compassion", "Forgiveness", "Emotional balance"],
    weaknesses: ["Difficulty trusting", "Fear of intimacy", "Codependency", "Emotional guardedness"],
    balanceSuggestions: [
      "Practice loving-kindness meditation",
      "Open your heart through yoga",
      "Spend time with loved ones and pets",
      "Practice forgiveness toward yourself and others",
      "Give and receive without expectation",
    ],
    meditationAdvice: "Visualize a beautiful emerald green light glowing in the center of your chest. Feel it opening like a flower, radiating love and compassion to all beings.",
    crystals: ["Rose Quartz", "Green Aventurine", "Jade", "Emerald", "Malachite"],
    affirmation: "I give and receive love freely. My heart is open, compassionate, and healed.",
  },
  throat: {
    name: "throat",
    title: "Throat Chakra",
    color: "#3b82f6",
    element: "Ether",
    location: "Throat",
    strengths: ["Authentic communication", "Clear expression", "Active listening", "Speaking one's truth"],
    weaknesses: ["Fear of speaking up", "Difficulty expressing needs", "Lying or withholding truth", "Feeling unheard"],
    balanceSuggestions: [
      "Practice honest self-expression",
      "Sing, chant, or hum daily",
      "Journal your thoughts freely",
      "Speak affirmations aloud",
      "Practice active listening",
    ],
    meditationAdvice: "Visualize a bright blue light in your throat. Feel your voice as a pure instrument of truth. Speak with clarity, honesty, and compassion.",
    crystals: ["Lapis Lazuli", "Sodalite", "Aquamarine", "Blue Lace Agate", "Turquoise"],
    affirmation: "I speak my truth with clarity, courage, and compassion. My voice matters.",
  },
  "third-eye": {
    name: "third-eye",
    title: "Third Eye Chakra",
    color: "#8b5cf6",
    element: "Light",
    location: "Forehead between brows",
    strengths: ["Intuition and insight", "Clear perception", "Imagination", "Wisdom beyond logic"],
    weaknesses: ["Overthinking", "Disconnection from intuition", "Illusions and confusion", "Resistance to inner knowing"],
    balanceSuggestions: [
      "Practice meditation and mindfulness",
      "Trust your gut feelings",
      "Limit screen time before sleep",
      "Keep a dream journal",
      "Practice visualization exercises",
    ],
    meditationAdvice: "Visualize an indigo light between your brows. Feel your inner vision awakening — see beyond the surface to the truth that lies within all things.",
    crystals: ["Amethyst", "Lapis Lazuli", "Fluorite", "Sugilite", "Charoite"],
    affirmation: "I trust my inner wisdom and see clearly with the eyes of intuition.",
  },
  crown: {
    name: "crown",
    title: "Crown Chakra",
    color: "#a855f7",
    element: "Cosmic",
    location: "Top of head",
    strengths: ["Spiritual connection", "Divine awareness", "Transcendence", "Universal consciousness"],
    weaknesses: ["Spiritual disconnection", "Cynicism", "Lack of purpose", "Feeling separate from source"],
    balanceSuggestions: [
      "Practice silent meditation",
      "Connect with something greater than yourself",
      "Study spiritual teachings",
      "Spend time in nature's cathedrals",
      "Practice gratitude and surrender",
    ],
    meditationAdvice: "Visualize a brilliant violet-white light at the crown of your head. Feel it opening like a thousand-petaled lotus, connecting you to the infinite cosmos.",
    crystals: ["Clear Quartz", "Selenite", "Amethyst", "Diamond", "Lepidolite"],
    affirmation: "I am one with the universe. I trust the divine wisdom that flows through me.",
  },
};
