import type { MoonSignData, ZodiacSign } from '@/types/cosmic';

export const MOON_SIGNS: Record<ZodiacSign, MoonSignData> = {
  aries: {
    sign: "aries",
    emotionalNature: "Emotions flare hot and fast like a wildfire. Aries Moon feels everything intensely but briefly — anger comes quick and passes just as fast.",
    hiddenFears: "Fear of being controlled, appearing weak, or losing independence.",
    relationshipPatterns: "Bold in romance, pursues passionately, needs space and excitement. May struggle with patience but is fiercely protective.",
    emotionalStrengths: ["Courage to confront feelings head-on", "Quick to forgive and move forward", "Emotionally honest and transparent"],
    intuition: "Gut-driven and instinctive. Makes snap judgments that are often correct.",
    subconscious: "Driven by primal impulses — the inner child runs wild and free.",
  },
  taurus: {
    sign: "taurus",
    emotionalNature: "Emotions are deep, steady, and slow to change. Taurus Moon needs security, comfort, and physical reassurance to feel safe.",
    hiddenFears: "Fear of financial instability, loss of comfort, and betrayal of trust.",
    relationshipPatterns: "Loyal, sensual, and devoted. Needs physical affection and consistency. Slow to open up but unwavering once committed.",
    emotionalStrengths: ["Emotionally stable and reliable", "Patient through emotional turmoil", "Deep capacity for lasting love"],
    intuition: "Practical intuition rooted in bodily sensations and gut feelings about people.",
    subconscious: "Stores memories through sensory experiences — scent, touch, taste trigger deep emotions.",
  },
  gemini: {
    sign: "gemini",
    emotionalNature: "Emotions are intellectualized and ever-changing. Gemini Moon processes feelings through talking, writing, and mental analysis.",
    hiddenFears: "Fear of boredom, being trapped, or running out of things to say.",
    relationshipPatterns: "Needs mental stimulation and variety. Flirtatious and playful. May seem emotionally inconsistent.",
    emotionalStrengths: ["Can talk through any emotional issue", "Adaptable to different emotional situations", "Curious about emotional growth"],
    intuition: "Quick flashes of insight followed by rational analysis. Intuition speaks through sudden ideas.",
    subconscious: "A library of voices, ideas, and memories constantly cross-referencing each other.",
  },
  cancer: {
    sign: "cancer",
    emotionalNature: "Emotions are deep, nurturing, and tidal. Cancer Moon feels everything profoundly and absorbs the emotions of others like a sponge.",
    hiddenFears: "Fear of abandonment, rejection, and being emotionally unprotected.",
    relationshipPatterns: "Nurturing, clingy, and deeply attached. Creates emotional bonds that feel like family. Needs constant reassurance.",
    emotionalStrengths: ["Exceptional emotional intelligence", "Deeply nurturing and supportive", "Psychic sensitivity to others' needs"],
    intuition: "Psychic-level intuition. Picks up on unspoken feelings and atmospheric shifts instantly.",
    subconscious: "The emotional ocean — memories are stored with intense feeling and never truly forgotten.",
  },
  leo: {
    sign: "leo",
    emotionalNature: "Emotions are warm, dramatic, and expressed with flair. Leo Moon needs to feel special, admired, and creatively fulfilled.",
    hiddenFears: "Fear of being ordinary, ignored, or unloved.",
    relationshipPatterns: "Romantic, generous, and theatrical. Needs admiration and appreciation. Gives grand gestures and expects the same.",
    emotionalStrengths: ["Warm-hearted and generous with love", "Confident emotional expression", "Loyal and protective of loved ones"],
    intuition: "Dramatic inner knowing — intuition speaks through the heart and creative inspiration.",
    subconscious: "A grand stage where the inner child performs. All emotions are amplified for maximum impact.",
  },
  virgo: {
    sign: "virgo",
    emotionalNature: "Emotions are analyzed, categorized, and managed. Virgo Moon seeks order in feelings and worries about getting it right.",
    hiddenFears: "Fear of imperfection, being judged inadequate, or losing control.",
    relationshipPatterns: "Expresses love through acts of service. Can be critical but deeply devoted. Needs to feel useful.",
    emotionalStrengths: ["Practical problem-solving in emotional crises", "Attentive to partner's needs", "Continuous self-improvement"],
    intuition: "Discernment — a sharp inner critic that distinguishes truth from illusion.",
    subconscious: "A filing system of past experiences, constantly organizing and optimizing emotional responses.",
  },
  libra: {
    sign: "libra",
    emotionalNature: "Emotions are filtered through a desire for harmony and beauty. Libra Moon avoids conflict and seeks peaceful resolution.",
    hiddenFears: "Fear of conflict, being alone, or making the wrong choice.",
    relationshipPatterns: "Romantic, charming, and partnership-oriented. May avoid difficult conversations to keep the peace.",
    emotionalStrengths: ["Diplomatic in emotional conflicts", "Natural peacemaker", "Sees all sides of an issue"],
    intuition: "Relational intuition — knows exactly what to say to restore harmony and balance.",
    subconscious: "A scale constantly weighing emotional options, seeking the most beautiful and balanced path forward.",
  },
  scorpio: {
    sign: "scorpio",
    emotionalNature: "Emotions are volcanic, intense, and all-consuming. Scorpio Moon feels everything at maximum depth and intensity.",
    hiddenFears: "Fear of betrayal, losing control, and emotional exposure.",
    relationshipPatterns: "Passionate, possessive, and transformative. Forms soul-deep bonds. Trust must be earned absolutely.",
    emotionalStrengths: ["Extraordinary emotional depth and resilience", "Ability to transform through pain", "Unwavering loyalty"],
    intuition: "Penetrating intuition that sees through lies and hidden motives instantly.",
    subconscious: "The underworld — a realm of shadows, buried truths, and immense psychic power waiting to be harnessed.",
  },
  sagittarius: {
    sign: "sagittarius",
    emotionalNature: "Emotions are optimistic, adventurous, and freedom-seeking. Sagittarius Moon needs space to roam and explore.",
    hiddenFears: "Fear of being trapped, suffocated, or forced into a routine.",
    relationshipPatterns: "Fun-loving, honest, and independent. Needs a partner who values freedom. May avoid emotional heaviness.",
    emotionalStrengths: ["Can find humor in any situation", "Philosophical perspective on pain", "Inspires others with optimism"],
    intuition: "Prophetic intuition — senses where life is heading and trusts the journey.",
    subconscious: "A vast wilderness of unexplored territories, always seeking the next horizon.",
  },
  capricorn: {
    sign: "capricorn",
    emotionalNature: "Emotions are controlled, reserved, and channeled into achievement. Capricorn Moon builds walls of self-sufficiency.",
    hiddenFears: "Fear of failure, inadequacy, and losing status or respect.",
    relationshipPatterns: "Responsible, committed, and cautious. Expresses love through provision and reliability.",
    emotionalStrengths: ["Emotional discipline and maturity", "Can handle any crisis with composure", "Deep sense of duty to loved ones"],
    intuition: "Strategic intuition — a gut feeling for what will work in the long run.",
    subconscious: "A mountain of responsibilities and buried feelings. Emotions are stored in the body until safely expressed.",
  },
  aquarius: {
    sign: "aquarius",
    emotionalNature: "Emotions are processed intellectually and often detached. Aquarius Moon values freedom of feeling and unconventional expression.",
    hiddenFears: "Fear of emotional engulfment, losing individuality, or being ordinary.",
    relationshipPatterns: "Needs intellectual connection and personal space. May seem aloof but cares deeply about humanity.",
    emotionalStrengths: ["Objectivity in emotional situations", "Progressive approach to relationships", "Loyal to friends and causes"],
    intuition: "Flash of genius intuition — sudden insights that seem to come from the collective consciousness.",
    subconscious: "A network connected to the collective unconscious. Thoughts and feelings are not entirely personal.",
  },
  pisces: {
    sign: "pisces",
    emotionalNature: "Emotions are boundless, dreamy, and deeply compassionate. Pisces Moon absorbs the world's pain and joy like an ocean.",
    hiddenFears: "Fear of harsh reality, being overwhelmed, and losing themselves in others.",
    relationshipPatterns: "Romantic, selfless, and spiritually connected. May struggle with boundaries but loves unconditionally.",
    emotionalStrengths: ["Boundless compassion and empathy", "Artistic emotional expression", "Spiritual depth and wisdom"],
    intuition: "Direct channel to the divine. Intuition speaks through dreams, art, and sudden knowing.",
    subconscious: "The cosmic ocean — all souls are connected in the watery depths of universal consciousness.",
  },
};
