import type { MoonSignData, ZodiacSign } from '@/types/cosmic';

export const MOON_SIGNS: Record<ZodiacSign, MoonSignData> = {
  aries: {
    sign: "aries",
    emotionalNature: "Emotions erupt quickly and intensely, like a wildfire — passionate, impulsive, and honest. An Aries Moon feels everything in the moment and expresses feelings without filter.",
    hiddenFears: "Fear of vulnerability, being controlled, or appearing weak. Beneath the bold exterior lies a deep fear of not being enough.",
    relationshipPatterns: "Attracted to confident, independent partners who can match their energy. Needs excitement and spontaneity; boredom is the relationship killer.",
    emotionalStrengths: ["Courageous honesty about feelings", "Quick to forgive and move on", "Inspires others with emotional bravery", "Refuses to dwell in victimhood"],
    intuition: "Gut-level, instinctive knowing — trusts the first impulse and acts on it without hesitation.",
    subconscious: "Driven by primal urges for autonomy and self-assertion. The inner child is a fearless warrior who needs to lead.",
  },
  taurus: {
    sign: "taurus",
    emotionalNature: "Deep, steady, and slow to stir. A Taurus Moon feels emotions in the body and needs physical comfort to process. Once upset, takes time to return to calm.",
    hiddenFears: "Fear of instability, financial ruin, and losing loved ones. Clings to the familiar because change feels like a threat to survival.",
    relationshipPatterns: "Needs security, consistency, and physical affection. Builds trust slowly but loves deeply once committed. Jealousy and possessiveness can surface.",
    emotionalStrengths: ["Unshakable loyalty and devotion", "Patient through emotional storms", "Grounded presence that calms others", "Protective of loved ones' feelings"],
    intuition: "Sensual, body-based knowing — reads energy through physical presence and gut comfort levels.",
    subconscious: "Programmed for preservation and pleasure. The inner self craves safety, sensuality, and the peace of a stable home.",
  },
  gemini: {
    sign: "gemini",
    emotionalNature: "Emotions are processed through the mind first — analyzing, labeling, talking through feelings rather than simply feeling them. Can seem detached when overwhelmed.",
    hiddenFears: "Fear of being trapped, bored, or intellectually underestimated. Deep down, fears that no one truly understands their multifaceted nature.",
    relationshipPatterns: "Attracted to witty, stimulating partners. Needs intellectual connection above all. May struggle with emotional depth, preferring lighthearted interaction.",
    emotionalStrengths: ["Can articulate feelings with precision", "Adaptable to others' emotional needs", "Curious about emotional growth", "Uses humor to diffuse tension"],
    intuition: "Mental flashes of insight — intuitive hits come as sudden ideas, synchronicities, or a knowing that arrives through words.",
    subconscious: "A restless library of information, always cross-referencing. The inner self is a curious student forever asking 'why?'.",
  },
  cancer: {
    sign: "cancer",
    emotionalNature: "Emotions flow like the tides — deep, powerful, and cyclical. A Cancer Moon feels everything profoundly and is highly attuned to the emotional atmosphere around them.",
    hiddenFears: "Fear of abandonment, rejection, and not being needed. The deepest fear is being left alone with no one to nurture or be nurtured by.",
    relationshipPatterns: "Seeks a partner who provides emotional security and family-like bonds. Nurtures intensely and expects the same in return. Can become clingy when insecure.",
    emotionalStrengths: ["Extraordinary empathy and emotional intelligence", "Nurtures others through difficult times", "Creates safe emotional spaces", "Intuitive understanding of unspoken needs"],
    intuition: "Psychic-level sensitivity — reads emotions, moods, and unspoken energy like a book. Intuition comes through feeling and gut knowing.",
    subconscious: "An ocean of ancestral memory and emotional history. The inner self is a tender child who needs to feel held and safe.",
  },
  leo: {
    sign: "leo",
    emotionalNature: "Emotions are dramatic, warm, and expressed with theatrical flair. A Leo Moon needs to feel special, appreciated, and seen. Pride is the strongest emotional driver.",
    hiddenFears: "Fear of being ordinary, ignored, or unloved. The deepest wound is feeling invisible or unappreciated.",
    relationshipPatterns: "Needs admiration, attention, and grand romantic gestures. Gives generously but expects recognition in return. Can be demanding when feeling unloved.",
    emotionalStrengths: ["Generous with love and affection", "Loyal to the core", "Lifts others' spirits with warmth", "Courageous in expressing feelings"],
    intuition: "Heart-centered knowing — intuition speaks through the chest, through feelings of warmth or contraction around people and situations.",
    subconscious: "A radiant palace where the inner self is king or queen. Needs to be adored but also deeply wants to be seen for who they truly are.",
  },
  virgo: {
    sign: "virgo",
    emotionalNature: "Emotions are filtered through analysis and a desire to be helpful. A Virgo Moon processes feelings by organizing, fixing, or serving others. Can intellectualize feelings to avoid overwhelm.",
    hiddenFears: "Fear of imperfection, being judged inadequate, and losing control. The inner critic is relentless.",
    relationshipPatterns: "Expresses love through acts of service and attention to detail. Needs a partner who appreciates thoughtfulness and doesn't mistake reserve for coldness.",
    emotionalStrengths: ["Thorough at working through emotional issues", "Practical and grounded in crises", "Reliable and consistent support", "Self-aware and committed to growth"],
    intuition: "Analytical intuition — pieces together subtle clues and patterns that others miss. Intuitive hits arrive as a quiet, certain knowing.",
    subconscious: "A meticulous workshop where everything has its place. The inner self is a perfectionist seeking to heal through order and usefulness.",
  },
  libra: {
    sign: "libra",
    emotionalNature: "Emotions are processed through relationships and a need for harmony. A Libra Moon dislikes conflict and may suppress feelings to keep the peace.",
    hiddenFears: "Fear of being alone, making the wrong choice, and being seen as unfair or unlovable.",
    relationshipPatterns: "Thrives in partnership — needs a companion to share life with. Can be indecisive and may avoid difficult emotional conversations.",
    emotionalStrengths: ["Diplomatic and fair in emotional disputes", "Creates harmonious environments", "Sees all sides of a situation", "Romantic and idealistic about love"],
    intuition: "Relational intuition — knows what others need and feels the energy between people. Intuitive hits come through a sense of harmony or dissonance.",
    subconscious: "A beautiful gallery seeking balance and beauty. The inner self longs for love, partnership, and the peace of perfect equilibrium.",
  },
  scorpio: {
    sign: "scorpio",
    emotionalNature: "Emotions run deep, dark, and intensely transformative. A Scorpio Moon feels everything at maximum volume but reveals only what they choose. Passion and pain are familiar companions.",
    hiddenFears: "Fear of betrayal, powerlessness, and being emotionally exposed. The deepest fear is having their vulnerabilities used against them.",
    relationshipPatterns: "Seeks soul-level connection and total emotional honesty. Demands loyalty and will test partners. Can be jealous, possessive, and secretive.",
    emotionalStrengths: ["Exceptional emotional depth and resilience", "Ability to transform through pain", "Loyal beyond measure", "Sees through lies and pretense"],
    intuition: "Penetrating, almost psychic knowing — reads people's true intentions. Intuition arrives as an undeniable gut feeling that cuts through all illusion.",
    subconscious: "A hidden ocean of power, shadow, and buried treasure. The inner self is a phoenix, constantly dying and being reborn.",
  },
  sagittarius: {
    sign: "sagittarius",
    emotionalNature: "Emotions are free-spirited, optimistic, and truth-seeking. A Sagittarius Moon needs freedom to process feelings and may deflect depth with humor or philosophy.",
    hiddenFears: "Fear of being trapped, tied down, or having their freedom taken away. Deep down, fears missing out on life.",
    relationshipPatterns: "Needs a partner who is also a best friend and adventure companion. Commitment can feel like a cage unless the relationship offers room to grow.",
    emotionalStrengths: ["Optimistic outlook even in hard times", "Honest about feelings", "Encourages growth and exploration", "Bounces back quickly from setbacks"],
    intuition: "Expansive, visionary knowing — intuition comes through a sense of higher purpose and gut feelings about what is true.",
    subconscious: "A vast frontier always calling toward the horizon. The inner self is an explorer seeking truth, meaning, and the freedom to roam.",
  },
  capricorn: {
    sign: "capricorn",
    emotionalNature: "Emotions are controlled, disciplined, and expressed with restraint. A Capricorn Moon values emotional maturity and may suppress feelings to maintain composure.",
    hiddenFears: "Fear of failure, inadequacy, and losing status. The deepest fear is being seen as incompetent or irresponsible.",
    relationshipPatterns: "Takes relationships seriously and builds slowly. Needs a partner who is responsible, ambitious, and understands their drive. Struggles with spontaneous emotional expression.",
    emotionalStrengths: ["Emotionally disciplined and mature", "Handles crises with calm practicality", "Loyal and dependable", "Builds lasting emotional foundations"],
    intuition: "Practical, grounded knowing — intuition speaks through a sense of timing and strategic foresight. Trusts what has proven true.",
    subconscious: "A mountain fortress built through discipline and hard-won wisdom. The inner self is an elder, wise but guarded.",
  },
  aquarius: {
    sign: "aquarius",
    emotionalNature: "Emotions are processed through the mind and filtered through a humanitarian lens. An Aquarius Moon can seem detached, valuing logic over emotional displays.",
    hiddenFears: "Fear of being ordinary, emotionally suffocated, or forced to conform. Deep down, fears being unable to connect authentically.",
    relationshipPatterns: "Needs intellectual stimulation and personal freedom in relationships. Can be emotionally unpredictable and struggles with traditional romantic expectations.",
    emotionalStrengths: ["Objective and fair in emotional situations", "Open-minded and non-judgmental", "Loyal to friends and causes", "Innovative approach to relationship problems"],
    intuition: "Electric, sudden flashes of insight — intuition arrives as a download from the collective consciousness. Knows things without knowing how.",
    subconscious: "A network of light connecting all of humanity. The inner self is a visionary who belongs to the collective, not to any one person.",
  },
  pisces: {
    sign: "pisces",
    emotionalNature: "Emotions are fluid, boundless, and deeply empathic. A Pisces Moon absorbs the feelings of others and can struggle to distinguish their own emotions from those around them.",
    hiddenFears: "Fear of harsh reality, being overwhelmed by the world, and losing themselves completely. Deep down, fears that their sensitivity is a curse.",
    relationshipPatterns: "Seeks a soulmate connection — a love that transcends the ordinary. Can be drawn to rescuing or being rescued. Needs a partner who provides gentle grounding.",
    emotionalStrengths: ["Boundless compassion and empathy", "Deeply intuitive and spiritually attuned", "Creative emotional expression", "Sees the beauty in everyone"],
    intuition: "Dreamlike, psychic knowing — receives information through dreams, symbols, and gut feelings. Intuition is their native language.",
    subconscious: "An infinite ocean where all souls are connected. The inner self is a mystic dreamer, dissolving boundaries to merge with the divine.",
  },
};
