import type { MoonPhaseData, MoonPhase } from '@/types/cosmic';

export const MOON_PHASES: Record<MoonPhase, MoonPhaseData> = {
  "new-moon": {
    phase: "new-moon",
    title: "New Moon",
    symbol: "🌑",
    interpretation: "The New Moon marks the beginning of the lunar cycle — a time of darkness, stillness, and potent new beginnings. Seeds of intention planted now will grow throughout the cycle. It is a time to rest, reflect, and set clear intentions for what you wish to manifest.",
    bestActivities: [
      "Setting intentions and goals for the month ahead",
      "Starting new projects and ventures",
      "Planting seeds — literally or metaphorically",
      "Quiet reflection and meditation",
      "Journaling about your deepest desires",
    ],
    energy: "Still, dark, introspective, potent with potential. The energy is inward and receptive — a time to listen rather than act.",
  },
  "waxing-crescent": {
    phase: "waxing-crescent",
    title: "Waxing Crescent",
    symbol: "🌒",
    interpretation: "A sliver of light returns to the sky. This is the phase of intention-taking-form. The seeds planted at the New Moon are beginning to sprout. Hope returns, and the first steps toward your goals are taken. Momentum is building.",
    bestActivities: [
      "Taking first steps toward your intentions",
      "Researching and gathering information",
      "Building momentum on new projects",
      "Visualizing your goals coming to life",
      "Making initial connections and introductions",
    ],
    energy: "Building, hopeful, initiating, fragile but growing. The energy is forward-moving but still gentle — nurture your beginnings.",
  },
  "first-quarter": {
    phase: "first-quarter",
    title: "First Quarter Moon",
    symbol: "🌓",
    interpretation: "Half illuminated, the First Quarter Moon brings a crisis point or decision. Challenges arise that test your commitment to the intentions set at the New Moon. This is the phase of action, effort, and overcoming obstacles.",
    bestActivities: [
      "Taking decisive action on your goals",
      "Overcoming obstacles and challenges",
      "Making important decisions",
      "Asserting yourself and your commitments",
      "Adjusting plans based on early results",
    ],
    energy: "Active, challenging, decisive, momentum-building. The energy requires effort and determination — push through resistance.",
  },
  "waxing-gibbous": {
    phase: "waxing-gibbous",
    title: "Waxing Gibbous Moon",
    symbol: "🌔",
    interpretation: "Nearly full, the Waxing Gibbous Moon is a time of refinement and preparation. You have come far since the New Moon, and now you fine-tune your approach. Adjust, perfect, and prepare for the illumination of the Full Moon.",
    bestActivities: [
      "Refining and perfecting your projects",
      "Analyzing progress and making adjustments",
      "Preparing for culmination and completion",
      "Seeking feedback and guidance",
      "Strengthening your skills and knowledge",
    ],
    energy: "Building, refining, anticipatory, analytical. The energy is about preparation and fine-tuning — get ready for the peak.",
  },
  "full-moon": {
    phase: "full-moon",
    title: "Full Moon",
    symbol: "🌕",
    interpretation: "The Moon is fully illuminated — a time of culmination, clarity, and peak energy. What began at the New Moon now reaches its peak. Emotions run high, truths are revealed, and magical energy is at its strongest. Celebrate achievements and release what no longer serves you.",
    bestActivities: [
      "Celebrating achievements and milestones",
      "Releasing what no longer serves you",
      "Harvesting the results of your efforts",
      "Performing rituals and ceremonies",
      "Expressing gratitude for abundance",
    ],
    energy: "Peak, illuminated, emotional, powerful, climactic. The energy is at its maximum — harvest, celebrate, and release.",
  },
  "waning-gibbous": {
    phase: "waning-gibbous",
    title: "Waning Gibbous Moon",
    symbol: "🌖",
    interpretation: "The light begins to fade, and the Waning Gibbous Moon is a time of gratitude, sharing, and teaching. You have harvested the lessons of the Full Moon. Now you share your wisdom, give thanks, and begin the slow process of letting go.",
    bestActivities: [
      "Sharing knowledge and teaching others",
      "Expressing gratitude for what you have received",
      "Giving back to your community",
      "Processing and integrating lessons learned",
      "Gentle completion of pending tasks",
    ],
    energy: "Thankful, sharing, winding down, reflective. The energy is about integration and generosity — pass on what you have learned.",
  },
  "last-quarter": {
    phase: "last-quarter",
    title: "Last Quarter Moon",
    symbol: "🌗",
    interpretation: "Half illuminated again, but now waning. The Last Quarter Moon is a time of release, forgiveness, and letting go. What is not serving your highest good falls away. This is a powerful time for clearing out the old to make space for the new cycle ahead.",
    bestActivities: [
      "Releasing old patterns and attachments",
      "Forgiving yourself and others",
      "Clearing clutter — physical, emotional, mental",
      "Completing unfinished business",
      "Resting and preparing for the new cycle",
    ],
    energy: "Releasing, clearing, forgiving, surrendering. The energy is about letting go — release with gratitude and trust.",
  },
  "waning-crescent": {
    phase: "waning-crescent",
    title: "Waning Crescent Moon",
    symbol: "🌘",
    interpretation: "The final sliver of light before darkness returns. The Waning Crescent Moon is the phase of surrender, rest, and deep healing. The cycle is complete. Rest in the darkness, integrate all that has happened, and trust the void before the new beginning.",
    bestActivities: [
      "Deep rest and rejuvenation",
      "Meditation and spiritual reflection",
      "Dreamwork and connecting with the subconscious",
      "Surrendering to the unknown",
      "Preparing quietly for the new cycle",
    ],
    energy: "Restful, surrendered, healing, dreamy. The energy is deeply inward — rest, heal, and trust the darkness before the new dawn.",
  },
};

export const MOON_PHASE_LIST: MoonPhaseData[] = Object.values(MOON_PHASES);
