import type { NumerologyInterpretation } from '@/types/cosmic';

export const NUMEROLOGY_INTERPRETATIONS: NumerologyInterpretation[] = [
  {
    number: 1,
    title: "The Leader",
    strengths: [
      "Independent and self-reliant — you trust your own judgment",
      "Natural born leader who initiates and inspires",
      "Innovative and original — you see new paths forward",
      "Ambitious and driven to achieve your goals",
      "Courageous — you take risks and forge ahead",
    ],
    weaknesses: [
      "Can be arrogant or domineering in leadership",
      "Struggles with collaboration and teamwork",
      "Impatient with slower-paced people and processes",
      "Tendency toward loneliness due to independence",
      "Can be overly competitive or aggressive",
    ],
    love: "You need a partner who respects your independence while offering warmth and affection. You are drawn to confident, self-assured individuals who have their own identity. In love, you are passionate and protective but must learn to compromise.",
    career: "You thrive in leadership roles, entrepreneurship, and positions where you can pioneer new ideas. You make an excellent CEO, founder, director, or creative lead. Avoid roles where you are micromanaged.",
    finances: "You are a natural earner with the drive to create wealth. Your independent spirit helps you find unique financial opportunities. Guard against impulsive investments and remember to save.",
    spiritualLessons: [
      "Learning to lead with humility and service",
      "Balancing independence with interdependence",
      "Trusting your unique path even when alone",
      "Using your power to uplift others",
    ],
    growthAreas: [
      "Develop patience and compassion for others",
      "Practice collaboration and shared leadership",
      "Learn to receive as well as give",
      "Cultivate humility alongside confidence",
    ],
  },
  {
    number: 2,
    title: "The Peacemaker",
    strengths: [
      "Deeply intuitive and sensitive to others' needs",
      "Excellent mediator who brings harmony to conflicts",
      "Cooperative and collaborative team player",
      "Patient and diplomatic in difficult situations",
      "Loyal and devoted in relationships",
    ],
    weaknesses: [
      "Overly sensitive to criticism and conflict",
      "Tendency to be codependent or people-pleasing",
      "Indecisive — struggles to make choices independently",
      "Can be shy or self-effacing",
      "Takes on others' emotional burdens too easily",
    ],
    love: "You are a devoted, caring partner who thrives in harmonious relationships. You need a partner who appreciates your gentle nature and offers steady reassurance. Your love is patient, kind, and deeply loyal.",
    career: "You excel in supportive, collaborative roles. Counseling, diplomacy, teaching, human resources, and any career that requires partnership suits you well. You thrive in environments with positive team dynamics.",
    finances: "You are cautious with money and prefer financial security. You may benefit from partnerships in financial matters. Guard against being taken advantage of financially due to your giving nature.",
    spiritualLessons: [
      "Learning to trust your intuition as divine guidance",
      "Balancing giving with receiving",
      "Finding your voice while honoring others",
      "Understanding that peace sometimes requires boundaries",
    ],
    growthAreas: [
      "Develop assertiveness and personal boundaries",
      "Learn to make decisions independently",
      "Practice self-care without guilt",
      "Honor your own needs as much as others",
    ],
  },
  {
    number: 3,
    title: "The Creative",
    strengths: [
      "Exceptionally creative and artistically gifted",
      "Charismatic and charming social presence",
      "Excellent communicator and storyteller",
      "Optimistic and joyful approach to life",
      "Inspiring to others through self-expression",
    ],
    weaknesses: [
      "Can be scattered and unfocused",
      "Tendency toward drama and emotional ups and downs",
      "Struggles with discipline and follow-through",
      "May use charm to avoid depth",
      "Sensitive to criticism of creative work",
    ],
    love: "You bring joy, excitement, and creative energy to relationships. You need a partner who appreciates your social nature and gives you freedom to express yourself. Your love is playful and inspiring.",
    career: "You thrive in creative fields — writing, art, performance, design, media, and communication. Teaching, public speaking, and any role that lets you express ideas suits you. Avoid overly structured or repetitive work.",
    finances: "Your creative talents can be highly lucrative, but you need discipline to manage money well. Consider automated savings and working with a financial planner.",
    spiritualLessons: [
      "Using your creative gifts in service of higher purpose",
      "Finding depth beneath the surface of joy",
      "Disciplining your talents to reach their full potential",
      "Expressing your soul through art and words",
    ],
    growthAreas: [
      "Develop focus and discipline",
      "Channel creativity into consistent practice",
      "Learn to find joy in solitude",
      "Balance social expression with inner reflection",
    ],
  },
  {
    number: 4,
    title: "The Builder",
    strengths: [
      "Hardworking, reliable, and incredibly disciplined",
      "Practical and grounded problem-solver",
      "Builds lasting foundations in every area of life",
      "Honest, trustworthy, and true to their word",
      "Patient and persistent through any challenge",
    ],
    weaknesses: [
      "Can be rigid and resistant to change",
      "Tendency toward workaholism and burnout",
      "May struggle with creativity and spontaneity",
      "Can be stubborn and closed to new ideas",
      "Prone to pessimism and worry",
    ],
    love: "You are a loyal, dependable partner who builds relationships on a foundation of trust and commitment. You express love through acts of service and practical support. You need a partner who appreciates stability.",
    career: "You excel in careers requiring discipline, structure, and practical skills. Engineering, construction, finance, project management, and any role that builds tangible value suits you.",
    finances: "You are a natural saver and long-term investor. Your disciplined approach builds wealth steadily. Guard against being too conservative — allow yourself to enjoy your earnings.",
    spiritualLessons: [
      "Finding the sacred in structure and discipline",
      "Learning flexibility within your foundations",
      "Understanding that rest is as important as work",
      "Building your inner life with the same care as your outer",
    ],
    growthAreas: [
      "Develop flexibility and openness to change",
      "Balance work with rest and play",
      "Practice trust in the process of life",
      "Cultivate faith beyond what you can see and control",
    ],
  },
  {
    number: 5,
    title: "The Adventurer",
    strengths: [
      "Freedom-loving and adventurous spirit",
      "Highly adaptable and versatile",
      "Excellent communicator and networker",
      "Embraces change and new experiences eagerly",
      "Charismatic and magnetic personality",
    ],
    weaknesses: [
      "Commitment-phobic — fears being tied down",
      "Restless and easily bored",
      "Can be irresponsible or unreliable",
      "Tendency toward excess and overindulgence",
      "Struggles with routine and consistency",
    ],
    love: "You need a partner who understands your need for freedom and adventure. Relationships must feel expansive, not restrictive. You are passionate and exciting but must work on commitment.",
    career: "You thrive in dynamic, varied careers. Sales, travel, media, marketing, event planning, and entrepreneurial ventures suit your versatile nature. Avoid monotonous, desk-bound roles.",
    finances: "Your adaptable nature can earn well through multiple streams. Guard against impulsive spending and lifestyle inflation. Build financial safety nets while keeping some freedom.",
    spiritualLessons: [
      "Finding freedom within commitment",
      "Using your versatility in service of growth",
      "Learning that true freedom is an inside job",
      "Balancing adventure with grounding",
    ],
    growthAreas: [
      "Develop commitment and follow-through",
      "Practice moderation and discipline",
      "Find adventure in depth, not just breadth",
      "Build stable foundations while keeping your freedom",
    ],
  },
  {
    number: 6,
    title: "The Nurturer",
    strengths: [
      "Deeply caring, nurturing, and compassionate",
      "Devoted to family, community, and loved ones",
      "Natural healer and counselor",
      "Responsible and dependable",
      "Creates beauty and harmony in home and relationships",
    ],
    weaknesses: [
      "Can be overly self-sacrificing",
      "Tendency to take on others' problems",
      "May become codependent or enabling",
      "Can be judgmental of those who don't meet responsibilities",
      "Struggles to set healthy boundaries",
    ],
    love: "You are the ultimate caregiver in relationships. Your love is expressed through service, devotion, and creating a beautiful home. You need a partner who appreciates your nurturing and gives back equally.",
    career: "You excel in helping professions — counseling, healthcare, teaching, social work, and community service. Any role where you care for others and create harmony suits you.",
    finances: "Generous to a fault, you happily spend on loved ones. Build financial boundaries that allow you to give without depleting yourself. Long-term security is important for your peace of mind.",
    spiritualLessons: [
      "Learning that self-care is not selfish",
      "Balancing giving with receiving",
      "Finding the divine in service to others",
      "Understanding that nurturing yourself is part of nurturing others",
    ],
    growthAreas: [
      "Develop healthy boundaries",
      "Learn to receive as well as give",
      "Practice self-care without guilt",
      "Allow others to take responsibility for themselves",
    ],
  },
  {
    number: 7,
    title: "The Seeker",
    strengths: [
      "Deeply analytical and intellectual",
      "Highly intuitive and spiritually attuned",
      "Natural researcher and truth-seeker",
      "Wise beyond years — possesses inner knowing",
      "Comfortable with solitude and introspection",
    ],
    weaknesses: [
      "Can be overly isolated and withdrawn",
      "Tendency toward skepticism and distrust",
      "May be emotionally distant or detached",
      "Can become lost in analysis without action",
      "Struggles with vulnerability and intimacy",
    ],
    love: "You need a partner who respects your need for solitude and intellectual depth. Trust builds slowly but deeply. You seek a soul connection that goes beyond the surface.",
    career: "You thrive in research, science, philosophy, technology, writing, and spiritual fields. Work that involves investigation, analysis, and discovery suits you perfectly.",
    finances: "You are analytical with money, preferring researched investments over speculation. You may undervalue your worth. Guard against over-caution that limits your abundance.",
    spiritualLessons: [
      "Trusting inner wisdom over external authorities",
      "Balancing knowledge with faith",
      "Opening the heart as well as the mind",
      "Sharing your wisdom with those who seek it",
    ],
    growthAreas: [
      "Develop trust in others and in life",
      "Balance solitude with meaningful connection",
      "Translate analysis into action",
      "Open your heart while honoring your mind",
    ],
  },
  {
    number: 8,
    title: "The Achiever",
    strengths: [
      "Highly ambitious and goal-oriented",
      "Natural executive and leadership abilities",
      "Excellent judgment in business and strategy",
      "Materially successful and abundance-minded",
      "Strong sense of personal authority",
    ],
    weaknesses: [
      "Can be overly focused on material success",
      "Tendency toward workaholism",
      "May be power-hungry or controlling",
      "Struggles with work-life balance",
      "Can be intimidating or domineering",
    ],
    love: "You seek a partner who matches your ambition and understands your drive. You are a provider and protector. Balance your professional intensity with tenderness in personal relationships.",
    career: "You are built for leadership, management, entrepreneurship, and executive roles. Finance, law, business ownership, and corporate leadership leverage your natural talents.",
    finances: "You have strong earning potential and business acumen. Wealth comes naturally through smart strategy. Guard against greed and remember that true abundance includes all areas of life.",
    spiritualLessons: [
      "Using power and wealth in service of good",
      "Balancing material and spiritual abundance",
      "Learning that true success includes love and health",
      "Leading with integrity and wisdom",
    ],
    growthAreas: [
      "Develop work-life balance",
      "Practice generosity and service",
      "Cultivate humility alongside success",
      "Remember that relationships matter more than results",
    ],
  },
  {
    number: 9,
    title: "The Humanitarian",
    strengths: [
      "Deeply compassionate and altruistic",
      "Broad-minded with global perspective",
      "Naturally wise and philosophical",
      "Creative and artistically gifted",
      "Powerful ability to inspire and uplift others",
    ],
    weaknesses: [
      "Can be overly idealistic and impractical",
      "Tendency to sacrifice personal needs for others",
      "May struggle with letting go of the past",
      "Can be emotionally intense or dramatic",
      "May feel burdened by the world's suffering",
    ],
    love: "You seek a partner who shares your ideals and passion for making a difference. Your love is unconditional and accepting. You need someone who grounds you while supporting your bigger vision.",
    career: "You excel in humanitarian work, teaching, counseling, arts, and any role that serves humanity. Non-profits, education, creative arts, and healing professions suit your compassionate nature.",
    finances: "Money is a tool for you — a means to help others and create change. You may struggle with personal wealth accumulation. Find balance between generosity and personal security.",
    spiritualLessons: [
      "Embracing forgiveness and letting go",
      "Balancing compassion for others with self-compassion",
      "Using your wisdom to serve the greater good",
      "Understanding that you cannot pour from an empty cup",
    ],
    growthAreas: [
      "Practice self-care and boundaries",
      "Balance idealism with practical action",
      "Learn to release the past completely",
      "Accept that you cannot save everyone",
    ],
  },
  {
    number: 11,
    title: "The Master Teacher (Master Number)",
    strengths: [
      "Highly intuitive and spiritually awakened",
      "Inspirational presence that uplifts others",
      "Deep creative and visionary abilities",
      "Natural healer and guide",
      "Access to higher wisdom and insight",
    ],
    weaknesses: [
      "Overwhelmed by sensitivity and intensity",
      "Nervous energy and anxiety",
      "Struggles with grounding and practicality",
      "Can feel isolated by unique perspective",
      "Perfectionist tendencies create pressure",
    ],
    love: "You seek a soulmate-level connection. Your relationships are intense, transformative, and deeply spiritual. You need a partner who understands your sensitivity and supports your higher calling.",
    career: "You are called to teaching, healing, creative arts, or spiritual guidance. Any role where you inspire and elevate others aligns with your purpose.",
    finances: "Wealth comes through your inspired work rather than conventional channels. Trust that following your purpose will provide. Guard against financial instability during creative periods.",
    spiritualLessons: [
      "Integrating spiritual gifts with practical living",
      "Using your light to illuminate the path for others",
      "Accepting your sensitivity as a gift, not a burden",
      "Balancing visionary ideals with grounded action",
    ],
    growthAreas: [
      "Develop grounding practices",
      "Learn to manage your sensitive energy",
      "Balance spiritual and material worlds",
      "Trust your unique vision even when others don't understand",
    ],
  },
  {
    number: 22,
    title: "The Master Builder (Master Number)",
    strengths: [
      "Visionary who can manifest dreams into reality",
      "Exceptional practical and organizational skills",
      "Natural leader with global impact potential",
      "Combines big-picture vision with detailed execution",
      "Inspires others to build alongside them",
    ],
    weaknesses: [
      "Overwhelmed by the weight of their own potential",
      "Can be controlling and perfectionistic",
      "Struggles with delegating and trusting others",
      "May feel burdened by their mission",
      "Can become cynical if ideals are not realized",
    ],
    love: "You need a partner who supports your grand vision while providing grounding and stability. You are a builder not just of structures but of relationships. Find someone who believes in your dreams.",
    career: "You are designed for ambitious, world-impacting work — large-scale projects, architecture, politics, major business ventures, or global organizations.",
    finances: "You have tremendous wealth-building potential. Your visions require resources, and you have the ability to manifest them. Balance grand vision with practical financial management.",
    spiritualLessons: [
      "Channeling your power in service of the greater good",
      "Learning to build with patience and precision",
      "Trusting the process of manifestation",
      "Using your gifts to create lasting positive change",
    ],
    growthAreas: [
      "Develop patience with the manifestation process",
      "Learn to delegate and trust collaborators",
      "Balance ambition with self-care",
      "Stay grounded while thinking big",
    ],
  },
  {
    number: 33,
    title: "The Master Teacher of Love (Master Number)",
    strengths: [
      "Embodies unconditional love and compassion",
      "Deep spiritual wisdom and understanding",
      "Natural healer and comforter of others",
      "Inspiring presence that elevates collective consciousness",
      "Selfless dedication to serving humanity",
    ],
    weaknesses: [
      "Can become overwhelmed by compassion fatigue",
      "May sacrifice personal needs excessively",
      "Struggles with boundaries in relationships",
      "Carries the weight of others' suffering",
      "Can feel isolated by their high spiritual calling",
    ],
    love: "Your love is unconditional, transformative, and healing. You seek a partner who shares your spiritual values and supports your mission. Your relationships are meant to heal and uplift.",
    career: "You are called to careers of profound service — spiritual teaching, healing arts, humanitarian leadership, or creative work that elevates consciousness.",
    finances: "You attract resources through your service to others. Money flows through you, not to you, for the benefit of others. Guard against financial self-neglect.",
    spiritualLessons: [
      "Your main lesson is love — giving and receiving it unconditionally",
      "Balancing service to humanity with service to self",
      "Learning that self-love enables greater love for others",
      "Accepting your role as a light-worker in the world",
    ],
    growthAreas: [
      "Develop sacred self-care practices",
      "Learn to receive as much as you give",
      "Set compassionate boundaries",
      "Trust that your light is enough — you do not need to save everyone",
    ],
  },
];

export const NUMEROLOGY_BY_NUMBER: Record<number, NumerologyInterpretation> =
  Object.fromEntries(NUMEROLOGY_INTERPRETATIONS.map((n) => [n.number, n]));

export function findNumerologyInterpretation(num: number): NumerologyInterpretation | undefined {
  return NUMEROLOGY_BY_NUMBER[num];
}
