import type { PlanetData, PlanetName } from '@/types/cosmic';

export const PLANETS: Record<PlanetName, PlanetData> = {
  sun: {
    planet: "sun",
    title: "The Sun",
    rules: "Core identity, ego, vitality, and life purpose.",
    influence: "The Sun represents your fundamental self — who you are at your core. It governs your willpower, self-expression, and the unique light you bring to the world.",
    strengths: ["Confidence and self-assurance", "Vitality and life force", "Creative self-expression", "Leadership ability", "Generosity of spirit"],
    weaknesses: ["Arrogance and ego inflation", "Need for constant validation", "Difficulty taking criticism", "Dramatic tendencies"],
    color: "Gold",
    day: "Sunday",
  },
  moon: {
    planet: "moon",
    title: "The Moon",
    rules: "Emotions, instincts, habits, and the subconscious mind.",
    influence: "The Moon governs your emotional nature and how you respond to life instinctively. It reveals your deepest needs, your nurturing style, and how you seek comfort.",
    strengths: ["Emotional intelligence", "Intuitive sensitivity", "Nurturing ability", "Adaptability to change", "Deep empathy"],
    weaknesses: ["Moodiness and emotional instability", "Over-sensitivity", "Clinginess in relationships", "Difficulty letting go"],
    color: "Silver",
    day: "Monday",
  },
  mercury: {
    planet: "mercury",
    title: "Mercury",
    rules: "Communication, intellect, perception, and information processing.",
    influence: "Mercury shapes how you think, speak, write, and process information. It governs your learning style, curiosity, and how you express ideas.",
    strengths: ["Quick thinking and wit", "Excellent communication", "Adaptability and versatility", "Love of learning", "Problem-solving ability"],
    weaknesses: ["Overthinking and anxiety", "Superficiality", "Nervous energy", "Difficulty focusing"],
    color: "Yellow",
    day: "Wednesday",
  },
  venus: {
    planet: "venus",
    title: "Venus",
    rules: "Love, beauty, relationships, values, and pleasure.",
    influence: "Venus dictates what you find beautiful, how you express affection, and what you value in relationships. It governs your romantic nature and aesthetic sensibilities.",
    strengths: ["Capacity for deep love", "Appreciation of beauty", "Social grace and charm", "Artistic talent", "Generosity"],
    weaknesses: ["Vanity and superficiality", "People-pleasing tendencies", "Indecisiveness", "Overindulgence"],
    color: "Pink",
    day: "Friday",
  },
  mars: {
    planet: "mars",
    title: "Mars",
    rules: "Action, desire, energy, aggression, and ambition.",
    influence: "Mars represents your drive, ambition, and how you assert yourself. It governs your passion, courage, and the way you pursue what you want.",
    strengths: ["Courage and determination", "Physical energy and stamina", "Passionate pursuit of goals", "Competitive drive", "Initiative"],
    weaknesses: ["Aggression and impatience", "Recklessness", "Selfishness", "Tendency to conflict"],
    color: "Red",
    day: "Tuesday",
  },
  jupiter: {
    planet: "jupiter",
    title: "Jupiter",
    rules: "Expansion, wisdom, luck, growth, and higher learning.",
    influence: "Jupiter brings expansion to everything it touches. It governs your capacity for growth, optimism, wisdom, and the areas where you experience good fortune.",
    strengths: ["Optimism and faith", "Wisdom and vision", "Generosity", "Love of exploration", "Natural luck"],
    weaknesses: ["Overindulgence", "Reckless optimism", "Arrogance", "Scattered energy"],
    color: "Purple",
    day: "Thursday",
  },
  saturn: {
    planet: "saturn",
    title: "Saturn",
    rules: "Discipline, responsibility, structure, time, and life lessons.",
    influence: "Saturn represents the teacher of hard lessons. It governs your discipline, sense of responsibility, and the areas where you must work hardest to achieve mastery.",
    strengths: ["Discipline and self-control", "Patience and perseverance", "Wisdom through experience", "Reliability and responsibility", "Long-term vision"],
    weaknesses: ["Pessimism", "Rigidity and resistance to change", "Workaholic tendencies", "Emotional coldness"],
    color: "Dark Blue",
    day: "Saturday",
  },
  uranus: {
    planet: "uranus",
    title: "Uranus",
    rules: "Innovation, rebellion, change, and originality.",
    influence: "Uranus breaks the rules and shatters the status quo. It governs your urge for freedom, your unique genius, and the unexpected changes that awaken you.",
    strengths: ["Originality and innovation", "Independent thinking", "Embracing change", "Humanitarian ideals", "Inventive genius"],
    weaknesses: ["Unpredictability", "Rebelliousness for its own sake", "Emotional detachment", "Erratic behavior"],
    color: "Electric Blue",
    day: "Wednesday",
  },
  neptune: {
    planet: "neptune",
    title: "Neptune",
    rules: "Dreams, intuition, spirituality, illusion, and transcendence.",
    influence: "Neptune dissolves boundaries and connects you to the divine. It governs your dreams, spiritual sensitivity, artistic inspiration, and capacity for transcendence.",
    strengths: ["Spiritual depth and wisdom", "Artistic and creative genius", "Boundless compassion", "Dream recall and intuition", "Connection to the divine"],
    weaknesses: ["Escapism and addiction", "Confusion and delusion", "Martyrdom", "Lack of boundaries"],
    color: "Seafoam Green",
    day: "Thursday",
  },
  pluto: {
    planet: "pluto",
    title: "Pluto",
    rules: "Transformation, power, rebirth, and the subconscious depths.",
    influence: "Pluto governs the deepest forces of transformation — death and rebirth, power and control, and the uncovering of hidden truths. It rules your capacity for profound change.",
    strengths: ["Deep transformation ability", "Uncovering hidden truths", "Resilience and regeneration", "Intensity and focus", "Psychological depth"],
    weaknesses: ["Obsessive tendencies", "Power struggles", "Distrust and secrecy", "Inability to let go"],
    color: "Black",
    day: "Tuesday",
  },
};
