import type { PlanetData, PlanetName } from '@/types/cosmic';

export const PLANETS: Record<PlanetName, PlanetData> = {
  sun: {
    planet: "sun",
    title: "Sun",
    rules: "Core identity, ego, self-expression, vitality, and the conscious self. Represents your fundamental character and life force.",
    influence: "The Sun illuminates your purpose and drive. It governs your willpower, creativity, and how you shine in the world. A strong Sun brings confidence and leadership; a challenged Sun may show ego struggles.",
    strengths: ["Radiant confidence and self-expression", "Strong leadership abilities", "Creative vitality", "Generosity and warmth", "Clear sense of purpose"],
    weaknesses: ["Overbearing ego and arrogance", "Need for constant recognition", "Difficulty receiving feedback", "Dramatic tendencies"],
    color: "#FFD700",
    day: "Sunday",
  },
  moon: {
    planet: "moon",
    title: "Moon",
    rules: "Emotions, instincts, habits, the subconscious, and the inner self. Represents your emotional nature and how you nurture.",
    influence: "The Moon governs your emotional landscape and intuitive responses. It reveals how you react instinctively, what makes you feel secure, and your deepest emotional needs.",
    strengths: ["Deep emotional intelligence", "Nurturing and empathetic nature", "Strong intuition", "Adaptability to change", "Imagination and creativity"],
    weaknesses: ["Moodiness and emotional volatility", "Over-sensitivity", "Clinginess and insecurity", "Difficulty with objectivity"],
    color: "#C0C0C0",
    day: "Monday",
  },
  mercury: {
    planet: "mercury",
    title: "Mercury",
    rules: "Communication, intellect, reasoning, learning, and mental agility. Governs how you think, speak, and process information.",
    influence: "Mercury shapes your communication style, intellectual interests, and mental dexterity. It influences how you learn, teach, and exchange ideas with the world.",
    strengths: ["Quick thinking and mental agility", "Excellent communication skills", "Versatility and adaptability", "Problem-solving ability", "Love of learning"],
    weaknesses: ["Nervous energy and overthinking", "Tendency to be superficial", "Indecisiveness", "Manipulative communication"],
    color: "#FFBF00",
    day: "Wednesday",
  },
  venus: {
    planet: "venus",
    title: "Venus",
    rules: "Love, beauty, art, relationships, pleasure, values, and what you find harmonious. Governs attraction and aesthetic sense.",
    influence: "Venus reveals how you love, what you value, and your relationship with beauty and pleasure. It influences your romantic style, artistic talents, and capacity for joy.",
    strengths: ["Romantic and affectionate nature", "Appreciation of beauty and art", "Diplomacy and charm", "Generosity in relationships", "Strong values"],
    weaknesses: ["Vanity and materialism", "Indecision in relationships", "Pleasure-seeking and indulgence", "Conflict avoidance"],
    color: "#FF69B4",
    day: "Friday",
  },
  mars: {
    planet: "mars",
    title: "Mars",
    rules: "Action, desire, ambition, courage, aggression, and physical energy. Governs how you pursue what you want.",
    influence: "Mars drives your ambition, determination, and how you assert yourself. It rules your physical energy, competitive nature, and the way you channel anger and passion.",
    strengths: ["Courage and boldness", "Strong drive and ambition", "Passionate and energetic", "Competitive spirit", "Decisive action-taking"],
    weaknesses: ["Aggression and impulsiveness", "Impatience and recklessness", "Confrontational tendencies", "Difficulty with restraint"],
    color: "#FF0000",
    day: "Tuesday",
  },
  jupiter: {
    planet: "jupiter",
    title: "Jupiter",
    rules: "Expansion, abundance, wisdom, philosophy, higher learning, luck, and spiritual growth.",
    influence: "Jupiter brings growth, optimism, and expansion into your life. It governs where you experience luck, how you seek meaning, and your capacity for abundance and generosity.",
    strengths: ["Optimism and generosity", "Wisdom and philosophical depth", "Love of learning and exploration", "Abundance mindset", "Natural mentorship"],
    weaknesses: ["Overindulgence and excess", "Overconfidence and poor judgment", "Restlessness", "Dogmatic thinking"],
    color: "#FF8C00",
    day: "Thursday",
  },
  saturn: {
    planet: "saturn",
    title: "Saturn",
    rules: "Discipline, responsibility, structure, limitations, karma, time, and life lessons. Governs your greatest challenges and strengths.",
    influence: "Saturn represents the teacher of hard lessons. It governs your discipline, sense of responsibility, and the structures you build in life. Saturn returns mark major maturity milestones.",
    strengths: ["Discipline and self-control", "Responsibility and reliability", "Long-term planning", "Wisdom through experience", "Strong work ethic"],
    weaknesses: ["Rigidity and pessimism", "Fear of failure", "Emotional repression", "Workaholic tendencies"],
    color: "#2F4F4F",
    day: "Saturday",
  },
  uranus: {
    planet: "uranus",
    title: "Uranus",
    rules: "Innovation, rebellion, originality, sudden change, freedom, and awakening. Governs individuality and breakthroughs.",
    influence: "Uranus brings unexpected change, innovation, and liberation. It rules your unique genius, rebellious streak, and capacity for revolutionary thinking.",
    strengths: ["Originality and innovation", "Independence and freedom", "Progressive thinking", "Humanitarian ideals", "Embracing change"],
    weaknesses: ["Unpredictability and instability", "Rebellion for its own sake", "Emotional detachment", "Erratic behavior"],
    color: "#00CED1",
    day: "Wednesday",
  },
  neptune: {
    planet: "neptune",
    title: "Neptune",
    rules: "Dreams, intuition, spirituality, illusion, imagination, and transcendence. Governs the mystical and artistic realms.",
    influence: "Neptune dissolves boundaries and connects you to the divine. It rules your dreams, creative imagination, spiritual sensitivity, and capacity for transcendence — as well as confusion and deception.",
    strengths: ["Deep spiritual connection", "Artistic and creative genius", "Compassion and empathy", "Powerful imagination", "Mystical insight"],
    weaknesses: ["Escapism and addiction", "Confusion and deception", "Over-idealism", "Boundary dissolution"],
    color: "#4169E1",
    day: "Thursday",
  },
  pluto: {
    planet: "pluto",
    title: "Pluto",
    rules: "Transformation, power, death, rebirth, the subconscious, and regeneration. Governs profound change and hidden forces.",
    influence: "Pluto rules the deepest layers of transformation — death and rebirth, power dynamics, and the shadow self. It governs where you experience profound change and emerge stronger.",
    strengths: ["Extraordinary transformative power", "Deep psychological insight", "Resilience through crisis", "Uncovering hidden truths", "Personal regeneration"],
    weaknesses: ["Obsessive tendencies", "Power struggles and control", "Jealousy and possessiveness", "Difficulty letting go"],
    color: "#8B0000",
    day: "Tuesday",
  },
};

export const PLANET_LIST: PlanetData[] = Object.values(PLANETS);
