import type { RisingSignData, ZodiacSign } from '@/types/cosmic';

export const RISING_SIGNS: Record<ZodiacSign, RisingSignData> = {
  aries: {
    sign: "aries",
    firstImpressions: "Bold, energetic, and instantly noticeable. People perceive you as confident, direct, and ready for action. You walk into a room like you own it.",
    socialBehavior: "You take the initiative in social settings — starting conversations, suggesting plans, and leading the group. Competitive even in casual interactions.",
    appearanceTraits: ["Athletic or athletic build", "Strong eyebrows or facial features", "Active, purposeful walk", "Often wears red or bold colors", "Youthful appearance that ages well"],
    publicPersona: "A natural pioneer and leader. The world sees you as someone who gets things done, takes risks, and isn't afraid to be first.",
  },
  taurus: {
    sign: "taurus",
    firstImpressions: "Calm, grounded, and steady. People perceive you as reliable, composed, and someone who can be trusted. Your presence has a soothing effect.",
    socialBehavior: "You move with quiet confidence and don't feel the need to prove yourself. You enjoy good food, good company, and comfortable settings.",
    appearanceTraits: ["Solid, well-proportioned build", "Strong neck or jawline", "Expressive eyes", "Sense of style favors quality and comfort", "Graceful, deliberate movements"],
    publicPersona: "A dependable, sensual presence. The world sees you as someone who values quality, stability, and the finer things in life.",
  },
  gemini: {
    sign: "gemini",
    firstImpressions: "Lively, talkative, and intellectually engaging. People perceive you as clever, curious, and someone who always has something interesting to say.",
    socialBehavior: "You are the social butterfly — flitting between groups, sharing stories, and making connections. Your conversation is quick and witty.",
    appearanceTraits: ["Lean or youthful build", "Expressive hands when talking", "Bright, alert eyes", "Style changes frequently", "Often seen smiling or laughing"],
    publicPersona: "A curious communicator. The world sees you as intelligent, adaptable, and someone who knows a little about everything.",
  },
  cancer: {
    sign: "cancer",
    firstImpressions: "Warm, nurturing, and approachable. People perceive you as kind, empathetic, and someone who genuinely cares. Your face reveals your feelings.",
    socialBehavior: "You create a sense of home wherever you go. You naturally check in on others and make people feel comfortable and included.",
    appearanceTraits: ["Round or soft facial features", "Expressive, watery eyes", "Tendency toward softer fabrics", "Protective body language", "Comfortable, classic style"],
    publicPersona: "A caring, protective presence. The world sees you as someone who nurtures others and creates safe spaces.",
  },
  leo: {
    sign: "leo",
    firstImpressions: "Radiant, magnetic, and impossible to ignore. People perceive you as confident, charismatic, and someone who belongs in the spotlight.",
    socialBehavior: "You command attention naturally — you're the storyteller, the entertainer, the one people gather around. Your warmth draws others in.",
    appearanceTraits: ["Regal posture and presence", "Luxurious hair or mane-like quality", "Dramatic, expressive eyes", "Bold fashion choices", "Radiant, warm energy"],
    publicPersona: "A natural star and leader. The world sees you as generous, confident, and someone who lights up every room.",
  },
  virgo: {
    sign: "virgo",
    firstImpressions: "Polished, intelligent, and composed. People perceive you as capable, precise, and someone who has everything under control.",
    socialBehavior: "You are observant before engaging. You notice details others miss and offer thoughtful, practical contributions to conversations.",
    appearanceTraits: ["Clean, neat appearance", "Classic, understated style", "Attentive, analyzing eyes", "Well-groomed", "Poised and purposeful movements"],
    publicPersona: "A capable, refined presence. The world sees you as intelligent, reliable, and someone who pays attention to every detail.",
  },
  libra: {
    sign: "libra",
    firstImpressions: "Charming, graceful, and effortlessly likable. People perceive you as diplomatic, attractive, and someone who makes them feel at ease.",
    socialBehavior: "You are a natural diplomat — smoothing tensions, including everyone, and creating harmonious social environments. Your smile is disarming.",
    appearanceTraits: ["Pleasant, symmetrical features", "Elegant sense of style", "Warm, inviting smile", "Graceful movements", "Often well-dressed and accessorized"],
    publicPersona: "A charming diplomat. The world sees you as fair, balanced, and someone who brings people together.",
  },
  scorpio: {
    sign: "scorpio",
    firstImpressions: "Intense, mysterious, and magnetic. People perceive you as powerful, private, and someone with hidden depths. Your gaze is penetrating.",
    socialBehavior: "You observe more than you participate at first. When you speak, people listen. Your presence carries weight and intensity.",
    appearanceTraits: ["Intense, hypnotic eyes", "Magnetic presence", "Dark or striking coloring", "Controlled, deliberate movements", "Style often includes dark colors"],
    publicPersona: "An intense, transformative presence. The world sees you as mysterious, powerful, and someone not to be underestimated.",
  },
  sagittarius: {
    sign: "sagittarius",
    firstImpressions: "Enthusiastic, open, and adventurous. People perceive you as optimistic, honest, and someone who is always up for an adventure.",
    socialBehavior: "You are the life of the party — telling stories, making plans, and inspiring others with your excitement. Your laughter is contagious.",
    appearanceTraits: ["Athletic or active build", "Expressive, laughing eyes", "Relaxed, casual style", "Restless energy", "Often seen in motion"],
    publicPersona: "A free-spirited adventurer. The world sees you as optimistic, honest, and someone who lives life to the fullest.",
  },
  capricorn: {
    sign: "capricorn",
    firstImpressions: "Serious, composed, and authoritative. People perceive you as professional, capable, and someone who means business.",
    socialBehavior: "You are reserved in social settings, observing before engaging. When you speak, it is measured and meaningful. You command respect.",
    appearanceTraits: ["Classic, professional style", "Strong bone structure", " Serious, focused expression", "Well-tailored clothing", "Controlled posture"],
    publicPersona: "An ambitious achiever. The world sees you as disciplined, responsible, and someone who is climbing toward success.",
  },
  aquarius: {
    sign: "aquarius",
    firstImpressions: "Unique, unconventional, and intellectually intriguing. People perceive you as original, independent, and someone who thinks differently.",
    socialBehavior: "You are friendly but can seem detached. You engage deeply with ideas more than small talk. Your style and opinions are distinctly your own.",
    appearanceTraits: ["Unique or eclectic style", "Expressive, unusual eyes", " Hair color or style is often distinctive", "Individualistic fashion sense", "Body language is relaxed and unconventional"],
    publicPersona: "An innovative visionary. The world sees you as original, progressive, and someone who marches to their own drum.",
  },
  pisces: {
    sign: "pisces",
    firstImpressions: "Dreamy, gentle, and creatively expressive. People perceive you as artistic, empathetic, and someone with a rich inner world.",
    socialBehavior: "You are soft, kind, and accommodating in social settings. You absorb the energy around you and respond with empathy. May seem lost in thought.",
    appearanceTraits: ["Soft, dreamy eyes", "Ethereal or artistic style", "Flowing hair or clothing", "Gentle, fluid movements", "Expressive, sensitive face"],
    publicPersona: "A creative dreamer. The world sees you as artistic, compassionate, and someone who sees the world through a unique lens.",
  },
};
