import type { SpiritAnimal } from '@/types/cosmic';

export const SPIRIT_ANIMALS: SpiritAnimal[] = [
  {
    animal: "Wolf",
    traits: ["Loyal", "Intuitive", "Social", "Courageous", "Free-spirited"],
    lifeGuidance: "Trust your instincts and value your pack. You are a natural leader who thrives in community, but never forget your need for freedom and solitude.",
    strengths: ["Deep loyalty to tribe and family", "Sharp intuition that guides decisions", "Endurance through difficult seasons", "Natural leadership abilities"],
    spiritualMessage: "The Wolf teaches you to balance independence with community. Lead with your heart, trust your pack, and honor your wild spirit.",
    element: "Fire",
    direction: "West",
  },
  {
    animal: "Eagle",
    traits: ["Visionary", "Courageous", "Far-sighted", "Independent", "Spiritual"],
    lifeGuidance: "Rise above the noise to see the bigger picture. You are called to gain perspective, then descend with purpose to take action.",
    strengths: ["Sees the big picture when others are stuck in details", "Unparalleled courage and determination", "Ability to soar above challenges", "Spiritual connection and higher vision"],
    spiritualMessage: "The Eagle teaches you to rise above limitations. From a higher vantage point, solutions become visible. Soar, then strike with precision.",
    element: "Air",
    direction: "East",
  },
  {
    animal: "Lion",
    traits: ["Courageous", "Commanding", "Protective", "Confident", "Regal"],
    lifeGuidance: "Own your power and lead with authority. You are here to protect your pride, claim your territory, and live with royal confidence.",
    strengths: ["Natural authority that inspires respect", "Fearless in the face of challenges", "Protective of loved ones", "Magnificent presence and charisma"],
    spiritualMessage: "The Lion teaches you to roar your truth into the world. Stand in your power, protect what is yours, and lead with courage and grace.",
    element: "Fire",
    direction: "South",
  },
  {
    animal: "Fox",
    traits: ["Witty", "Adaptable", "Observant", "Clever", "Strategic"],
    lifeGuidance: "Navigate challenges with intelligence and adaptability. You have the gift of reading situations and finding creative solutions.",
    strengths: ["Quick thinking in complex situations", "Adaptability to changing circumstances", "Keen observation of human nature", "Strategic problem-solving"],
    spiritualMessage: "The Fox teaches you that wit and adaptability are your greatest weapons. Observe, adapt, and move with quiet precision.",
    element: "Earth",
    direction: "North",
  },
  {
    animal: "Owl",
    traits: ["Wise", "Observant", "Intuitive", "Mysterious", "Introspective"],
    lifeGuidance: "Look beneath the surface to find hidden truths. You see what others miss and possess ancient wisdom that guides your path.",
    strengths: ["Penetrating insight into hidden truths", "Exceptional wisdom and discernment", "Comfort with solitude and introspection", "Ability to navigate darkness"],
    spiritualMessage: "The Owl teaches you to see in the dark. When others are blind to the truth, your wisdom illuminates the hidden path forward.",
    element: "Air",
    direction: "North",
  },
  {
    animal: "Bear",
    traits: ["Strong", "Grounded", "Protective", "Introspective", "Resilient"],
    lifeGuidance: "Stand firm in your power and take time for introspection. You have inner strength that can weather any storm.",
    strengths: ["Tremendous physical and inner strength", "Deep connection to the natural world", "Fierce protection of boundaries", "Ability to retreat, heal, and emerge stronger"],
    spiritualMessage: "The Bear teaches you the power of stillness and strength. Know when to act, when to rest, and when to draw boundaries.",
    element: "Earth",
    direction: "West",
  },
  {
    animal: "Panther",
    traits: ["Powerful", "Mysterious", "Fearless", "Protective", "Graceful"],
    lifeGuidance: "Move through life with quiet power and grace. You are a guardian of sacred space, comfortable in the shadows and unafraid of the dark.",
    strengths: ["Silent, graceful power", "Fearlessness in facing darkness", "Guardianship of sacred boundaries", "Ability to navigate the unknown"],
    spiritualMessage: "The Panther teaches you to embrace your shadow and move through darkness with grace. Your power is quiet, your presence undeniable.",
    element: "Water",
    direction: "East",
  },
  {
    animal: "Dragon",
    traits: ["Powerful", "Transformative", "Protective", "Ancient", "Elemental"],
    lifeGuidance: "Embrace your transformative power. You are here to create change, protect sacred wisdom, and live with fire and purpose.",
    strengths: ["Immense personal power and presence", "Ability to transform challenges into strength", "Guardian of ancient wisdom", "Balances all elements within"],
    spiritualMessage: "The Dragon teaches you that true power comes from mastering all elements within yourself. Breathe fire into your purpose.",
    element: "Fire",
    direction: "East",
  },
  {
    animal: "Snake",
    traits: ["Transforming", "Healing", "Intuitive", "Patient", "Rebirth-oriented"],
    lifeGuidance: "Embrace the cycles of death and rebirth in your life. You are constantly shedding old skin to reveal a more authentic self.",
    strengths: ["Extraordinary capacity for transformation", "Deep intuitive and healing abilities", "Patience in waiting for the right moment", "Ability to release what no longer serves"],
    spiritualMessage: "The Snake teaches you the sacred art of letting go. Shed your old skin, heal your wounds, and be reborn into your truth.",
    element: "Water",
    direction: "South",
  },
  {
    animal: "Raven",
    traits: ["Intelligent", "Mysterious", "Transformative", "Communicative", "Visionary"],
    lifeGuidance: "You are a messenger between worlds. Your voice carries power and your vision pierces illusion. Speak the truth even when it is uncomfortable.",
    strengths: ["Keen intelligence and problem-solving", "Messenger of important truths", "Navigates between light and shadow", "Visionary perspective"],
    spiritualMessage: "The Raven teaches you to speak your truth and embrace the magic of transformation. You are the bridge between what was and what will be.",
    element: "Air",
    direction: "Northwest",
  },
  {
    animal: "Deer",
    traits: ["Gentle", "Intuitive", "Graceful", "Sensitive", "Peaceful"],
    lifeGuidance: "Move through life with gentleness and grace. Your sensitivity is your strength — trust your intuition and approach others with kindness.",
    strengths: ["Gentle strength that disarms hostility", "Keen sensitivity to surroundings", "Grace under pressure", "Ability to heal through presence"],
    spiritualMessage: "The Deer teaches you that true strength is gentle. Lead with kindness, trust your sensitive nature, and move with grace through every situation.",
    element: "Earth",
    direction: "Southeast",
  },
  {
    animal: "Hawk",
    traits: ["Observant", "Visionary", "Independent", "Courageous", "Spiritual"],
    lifeGuidance: "Keep your eyes on the horizon and trust your perspective. You have the ability to see opportunities and threats from afar.",
    strengths: ["Exceptional vision and awareness", "Ability to seize the right moment", "Independence and self-reliance", "Spiritual messenger energy"],
    spiritualMessage: "The Hawk teaches you to see clearly and act decisively. When the timing is right, dive with full commitment toward your goal.",
    element: "Air",
    direction: "Southeast",
  },
  {
    animal: "Horse",
    traits: ["Free", "Energetic", "Loyal", "Powerful", "Adventurous"],
    lifeGuidance: "Run toward your passions with wild freedom. You are a creature of movement, power, and loyalty. Do not let anyone tame your spirit.",
    strengths: ["Boundless energy and drive", "Fierce loyalty to those trusted", "Freedom-loving independent spirit", "Ability to carry others through hardship"],
    spiritualMessage: "The Horse teaches you to honor your need for freedom while carrying your responsibilities with strength. Run your own race.",
    element: "Fire",
    direction: "Southwest",
  },
  {
    animal: "Butterfly",
    traits: ["Transforming", "Joyful", "Delicate", "Colorful", "Evolving"],
    lifeGuidance: "Embrace the process of transformation. You are evolving through every stage of life — trust the journey and emerge in your full colors.",
    strengths: ["Embodies the beauty of change", "Lightness of being and joy", "Adaptability through life stages", "Ability to bring color to dark spaces"],
    spiritualMessage: "The Butterfly teaches you to trust the metamorphosis. You must be willing to dissolve before you can emerge as your truest self.",
    element: "Air",
    direction: "East",
  },
  {
    animal: "Turtle",
    traits: ["Patient", "Wise", "Persistent", "Grounded", "Ancient"],
    lifeGuidance: "Slow and steady wins the race. You carry your home within you and understand that true wisdom comes with time and persistence.",
    strengths: ["Patience that outlasts any challenge", "Deep connection to the Earth", "Protective wisdom and longevity", "Steady, unwavering progress"],
    spiritualMessage: "The Turtle teaches you that patience is not passive — it is persistent, grounded progress. Protect your peace and keep moving forward.",
    element: "Earth",
    direction: "Southwest",
  },
  {
    animal: "Phoenix",
    traits: ["Resilient", "Transformative", "Powerful", "Reborn", "Immortal"],
    lifeGuidance: "You have the power to rise from the ashes of any destruction. Every ending is the seed of your most powerful rebirth.",
    strengths: ["Extraordinary resilience and renewal", "Ability to transform pain into power", "Rises stronger after every fall", "Embodies the cycle of death and rebirth"],
    spiritualMessage: "The Phoenix teaches you that destruction is not the end — it is the furnace of transformation. Burn, rise, and soar higher than before.",
    element: "Fire",
    direction: "South",
  },
];

export const SPIRIT_ANIMAL_BY_NAME: Record<string, SpiritAnimal> =
  Object.fromEntries(SPIRIT_ANIMALS.map((a) => [a.animal.toLowerCase(), a]));

export function findSpiritAnimal(name: string): SpiritAnimal | undefined {
  return SPIRIT_ANIMAL_BY_NAME[name.toLowerCase()];
}
