// ============================================================
// COSMIC ORACLE — Western Zodiac, Moon, Rising, Elements & Planets
// ============================================================

import type {
  ZodiacSign,
  ZodiacData,
  MoonSignData,
  RisingSignData,
  ElementData,
  PlanetData,
  PlanetName,
  ZodiacElement,
} from '@/types/cosmic';

// ============================================================
// ZODIAC SIGNS — Complete Data for All 12 Signs
// ============================================================

export const ZODIAC_SIGNS: Record<ZodiacSign, ZodiacData> = {
  aries: {
    sign: "aries",
    symbol: "♈",
    dateRange: "March 21 – April 19",
    element: "fire",
    quality: "cardinal",
    rulingPlanet: "Mars",
    personality: [
      "Aries is the first sign of the zodiac, symbolizing the spark of life and the urge to begin. Those born under this sign are natural pioneers, driven by an innate desire to lead and explore.",
      "Bold, ambitious, and endlessly energetic, Aries individuals approach life with a fearless determination that inspires those around them. They are trailblazers who would rather ask forgiveness than permission.",
      "Their competitive nature fuels a relentless pursuit of their goals, but it also gives them an admirable resilience — they fall hard but get back up faster than anyone else.",
      "Impulsiveness is their double-edged sword: it grants them the courage to leap where others hesitate, but it can also lead to hasty decisions made in the heat of the moment.",
      "At their core, Aries souls crave authenticity. They despise pretense and value directness, often speaking their minds with a refreshing (if sometimes jarring) honesty.",
    ],
    strengths: [
      "Courageous — first to take risks and face challenges head-on",
      "Confident — possesses an unshakable belief in their own abilities",
      "Enthusiastic — infectious energy that motivates entire teams",
      "Honest — straightforward communication with no hidden agenda",
      "Independent — thrives on self-reliance and personal freedom",
      "Resourceful — finds creative solutions under pressure",
      "Passionate — throws their whole heart into everything they do",
    ],
    weaknesses: [
      "Impulsive — acts first, thinks second, especially when emotions run high",
      "Impatient — hates waiting and wants results immediately",
      "Aggressive — competitive drive can come across as confrontational",
      "Short-tempered — quick to anger, though equally quick to forgive",
      "Self-centered — can overlook others' needs when pursuing their vision",
      "Restless — struggles with routine and long-term commitment",
    ],
    loveStyle:
      "In love, Aries is an enthusiastic and passionate partner who pursues romance with the same fiery energy they bring to everything else. They love the thrill of the chase and are drawn to confident, independent partners who can match their intensity. Aries needs a relationship that feels like an adventure — routine and predictability are kryptonite. They are generous, protective, and fiercely loyal, but they need a partner who understands their need for independence and doesn't try to confine their wild spirit. Physical affection and spontaneous gestures of love keep the flame burning bright.",
    careerStyle:
      "Aries excels in careers that allow them to take initiative, lead teams, and break new ground. They thrive in fast-paced environments where quick decisions and bold moves are rewarded. Entrepreneurship, emergency services, sports, military leadership, sales, and any role that involves competition or pioneering are natural fits. Aries struggles in positions that require patience, bureaucracy, or following orders without question. They need autonomy, visible results, and the freedom to innovate on their own terms.",
    financialHabits:
      "Aries approaches money with bold enthusiasm — they are natural earners but impulsive spenders. They love the thrill of a new purchase and often reward themselves generously. Their financial strength lies in their ability to generate income through initiative and risk-taking. However, they need to cultivate patience in investing and avoid get-rich-quick schemes. Aries benefits from automated savings and a trusted advisor who can provide a grounding counterbalance to their impulsive financial instincts.",
    spiritualTraits: [
      "Seeks spiritual growth through action and experience rather than passive contemplation",
      "Believes in forging their own spiritual path rather than following established traditions",
      "Finds divine connection in moments of courage, adventure, and breakthrough",
      "Views challenges as spiritual lessons designed to strengthen the soul",
      "Natural leader in spiritual communities, inspiring others through example",
      "Values authenticity over orthodoxy in all spiritual matters",
    ],
    luckyNumbers: [1, 9, 19, 27, 36],
    luckyColors: ["Red", "Scarlet", "White", "Bright Gold"],
    luckyCrystals: ["Diamond", "Bloodstone", "Red Jasper", "Carnelian", "Garnet"],
    luckyDays: ["Tuesday", "Sunday"],
  },

  taurus: {
    sign: "taurus",
    symbol: "♉",
    dateRange: "April 20 – May 20",
    element: "earth",
    quality: "fixed",
    rulingPlanet: "Venus",
    personality: [
      "Taurus is the anchor of the zodiac — grounded, patient, and unfalteringly steady. Ruled by Venus, they possess a deep appreciation for beauty, comfort, and the finer things in life.",
      "Those born under this sign are builders at heart, creating lasting value through persistence and an unwavering work ethic. They understand that the best things take time to cultivate.",
      "Taurus individuals are deeply sensual beings who experience the world through touch, taste, and physical presence. They find joy in simple pleasures: good food, soft fabrics, warm sunlight, and genuine human connection.",
      "Their loyalty is legendary — once a Taurus commits to a person, cause, or goal, they see it through with remarkable dedication. This steadfastness makes them the rock that others lean on.",
      "Beneath their calm exterior lies a will of iron. Taurus is not easily swayed or intimidated, and when provoked, their stubbornness emerges as a formidable force of resistance.",
    ],
    strengths: [
      "Reliable — the person everyone counts on to show up and deliver",
      "Patient — willing to wait for the right moment and long-term results",
      "Determined — once set on a goal, virtually unstoppable",
      "Practical — brings grounded, realistic perspective to every situation",
      "Sensual — deeply connected to physical pleasures and aesthetic beauty",
      "Loyal — fiercely devoted to loved ones through thick and thin",
      "Generous — loves sharing their abundance with those they care about",
    ],
    weaknesses: [
      "Stubborn — resists change even when it's necessary for growth",
      "Possessive — can cling too tightly to people, possessions, and comfort zones",
      "Resistant to change — prefers the familiar and struggles with upheaval",
      "Materialistic — can place too much value on material wealth and status",
      "Indulgent — prone to overindulgence in food, drink, and luxury",
      "Lazy — when too comfortable, can sink into complacency",
    ],
    loveStyle:
      "Taurus loves with profound loyalty and devotion. They seek a partner who offers stability, sensual connection, and unwavering commitment. Romance for Taurus is expressed through tangible acts of care — cooking a beautiful meal, giving thoughtful gifts, building a comfortable home together. They are incredibly affectionate and sensual partners who value physical touch and quality time above all else. Taurus needs a relationship that feels safe and secure; trust is built slowly but once established, it is virtually unbreakable. Jealousy and possessiveness can surface if they feel threatened, but a secure Taurus is the most devoted partner imaginable.",
    careerStyle:
      "Taurus thrives in careers that offer stability, tangible results, and the opportunity to build something lasting. They excel in finance, banking, real estate, agriculture, architecture, design, culinary arts, and any field that combines practicality with beauty. Their patience and steady hand make them excellent project managers, craftspeople, and investors. Taurus works best in environments with clear expectations, consistent routines, and the autonomy to work at their own deliberate pace. They avoid chaotic, unstable work situations and value positions that reward long-term loyalty.",
    financialHabits:
      "Taurus has a natural gift for building wealth through patience and discipline. They are savers by nature who understand the power of compound interest and long-term investment. Taurus gravitates toward tangible assets — real estate, art, precious metals, and quality possessions that hold or increase in value. They enjoy spending on comfort and luxury but usually within a well-planned budget. Their challenge is avoiding overindulgence and learning to be flexible with financial strategies when circumstances change.",
    spiritualTraits: [
      "Connects to the divine through nature, physical presence, and the natural world",
      "Finds spiritual grounding in routine practices and rituals",
      "Believes the sacred dwells in everyday life — in food, touch, and beauty",
      "Values practical spirituality that can be lived, not just contemplated",
      "Seeks spiritual teachers and traditions with deep, established roots",
      "Uses sensory experiences — music, incense, candlelight — as gateways to transcendence",
    ],
    luckyNumbers: [2, 6, 15, 24, 33],
    luckyColors: ["Green", "Pink", "Light Blue", "Emerald"],
    luckyCrystals: ["Emerald", "Rose Quartz", "Lapis Lazuli", "Jade", "Malachite"],
    luckyDays: ["Friday", "Monday"],
  },

  gemini: {
    sign: "gemini",
    symbol: "♊",
    dateRange: "May 21 – June 20",
    element: "air",
    quality: "mutable",
    rulingPlanet: "Mercury",
    personality: [
      "Gemini is the messenger of the zodiac — quick-witted, curious, and endlessly fascinated by the world around them. Ruled by Mercury, they possess a mind that is always in motion, making connections and seeking understanding.",
      "Those born under this sign are natural communicators with a gift for language, storytelling, and intellectual exchange. They can talk their way into any room and charm anyone with their playful intelligence.",
      "The duality of Gemini is their defining trait — they contain multitudes, shifting between moods, interests, and perspectives with breathtaking fluidity. This makes them adaptable but can also puzzle those who try to pin them down.",
      "Gemini individuals are perpetual students of life, collecting knowledge and experiences like precious gems. Their curiosity is boundless, and they thrive on variety, novelty, and mental stimulation.",
      "At their best, Geminis are brilliant conversationalists, creative thinkers, and bridges between different worlds. Their gift is seeing multiple sides of every story and sharing those insights with others.",
    ],
    strengths: [
      "Versatile — adapts effortlessly to new situations and challenges",
      "Intelligent — quick mind with an insatiable hunger for knowledge",
      "Communicative — gifted speaker, writer, and storyteller",
      "Witty — sharp sense of humor that lights up any gathering",
      "Curious — perpetually interested in learning and exploring new ideas",
      "Youthful — maintains a playful, energetic approach to life",
      "Social — connects easily with people from all walks of life",
    ],
    weaknesses: [
      "Inconsistent — can be unreliable as interests shift frequently",
      "Superficial — may skim the surface rather than diving deep",
      "Indecisive — sees too many sides to commit to one path",
      "Nervous — an overactive mind can lead to anxiety and restlessness",
      "Moody — the dual nature can cause unpredictable emotional shifts",
      "Scattered — struggles to focus on one thing for extended periods",
    ],
    loveStyle:
      "Gemini approaches love as an intellectual and social adventure. They are drawn to partners who stimulate their mind, engage in lively debate, and share their love of exploration and variety. Communication is the heart of any Gemini relationship — they need a partner who can keep up with their quick wit and appreciate their need for stimulating conversation. Gemini values freedom and independence in relationships; they need space to explore their many interests. Boredom is their greatest enemy in love. A partner who is predictable, possessive, or unwilling to grow will quickly lose a Gemini's interest. They express love through words, ideas, and shared experiences rather than traditional romantic gestures.",
    careerStyle:
      "Gemini flourishes in careers that demand communication, adaptability, and intellectual engagement. Journalism, writing, teaching, sales, marketing, public relations, broadcasting, technology, and consulting are natural fits. They excel at roles that involve networking, gathering and disseminating information, and juggling multiple projects simultaneously. Gemini struggles in monotonous, repetitive work that offers no mental challenge. They need variety, social interaction, and the freedom to move between tasks. Remote work and flexible arrangements suit their restless spirit perfectly.",
    financialHabits:
      "Gemini's relationship with money is as varied as their interests. They are creative earners who may juggle multiple income streams simultaneously. Their spending can be impulsive, driven by curiosity and the desire to try new things. Geminis benefit from financial systems that allow flexibility while still maintaining structure — automated savings combined with discretionary funds for spontaneous purchases. Their greatest financial asset is their ability to learn quickly and adapt to changing markets. Their challenge is staying consistent with long-term financial plans and avoiding scattered investments.",
    spiritualTraits: [
      "Explores spirituality through study, reading, and intellectual inquiry",
      "Draws wisdom from multiple traditions rather than committing to one",
      "Communicates with the divine through writing, speech, and creative expression",
      "Seeks spiritual understanding through questioning, debate, and dialogue",
      "Believes truth is multifaceted and no single path holds all answers",
      "Finds sacred connection in libraries, classrooms, and conversations",
    ],
    luckyNumbers: [5, 7, 14, 21, 35],
    luckyColors: ["Yellow", "Light Green", "Silver", "Sky Blue"],
    luckyCrystals: ["Agate", "Citrine", "Tiger's Eye", "Moonstone", "Aquamarine"],
    luckyDays: ["Wednesday", "Sunday"],
  },

  cancer: {
    sign: "cancer",
    symbol: "♋",
    dateRange: "June 21 – July 22",
    element: "water",
    quality: "cardinal",
    rulingPlanet: "Moon",
    personality: [
      "Cancer is the heart of the zodiac — deeply emotional, intuitively attuned, and fiercely protective of those they love. Ruled by the Moon, their inner world ebbs and flows with the tides of feeling.",
      "Those born under this sign are natural nurturers with an extraordinary capacity for empathy and emotional understanding. They feel everything deeply and possess an almost psychic sensitivity to the moods of others.",
      "Home and family are sacred to Cancer. They create warm, welcoming sanctuaries where loved ones can find comfort, safety, and unconditional acceptance. Their love language is care — shown through food, protection, and presence.",
      "Cancers are fiercely loyal guardians of their inner circle. Once you earn a Cancer's trust, you have a champion for life — someone who will defend, support, and nourish you through every storm.",
      "Beneath their soft, caring exterior lies a protective shell. Cancer is vulnerable and easily hurt, but their emotional depth gives them a wellspring of strength that others can only marvel at.",
    ],
    strengths: [
      "Intuitive — possesses uncanny emotional intelligence and perception",
      "Nurturing — naturally cares for others with warmth and dedication",
      "Protective — fiercely loyal and defensive of loved ones",
      "Empathetic — feels others' emotions as if they were their own",
      "Imaginative — rich inner world fuels creativity and vision",
      "Tenacious — holds on with remarkable persistence once committed",
      "Resourceful — finds creative ways to provide and protect",
    ],
    weaknesses: [
      "Moody — emotions shift like the Moon, hard to predict or contain",
      "Overly sensitive — takes things personally and internalizes criticism",
      "Clingy — fears abandonment and can become emotionally dependent",
      "Passive-aggressive — avoids direct confrontation, expresses hurt indirectly",
      "Pessimistic — protective instincts can spiral into worst-case thinking",
      "Hold grudges — remembers every slight with remarkable clarity",
    ],
    loveStyle:
      "Cancer loves with their whole heart and then some. They seek a partner who provides emotional security, loyalty, and a sense of home. For Cancer, love is expressed through acts of service, quality time, and physical affection — cooking meals, offering a shoulder to cry on, building a life together. They need a partner who understands their emotional tides and doesn't retreat when they need extra reassurance. Trust is built slowly but once established, Cancer's devotion is absolute. They are vulnerable to heartbreak because they invest so deeply, but their capacity to love and nurture makes them one of the most giving partners in the zodiac.",
    careerStyle:
      "Cancer thrives in careers that involve caring for others, creating home-like environments, or tapping into their emotional intelligence. They excel in nursing, counseling, education, real estate, culinary arts, interior design, childcare, and hospitality. Water signs in general, Cancers are drawn to careers that feel meaningful and allow them to make a tangible difference in people's lives. They work best in environments that feel like a second home — supportive teams, nurturing leadership, and a sense of belonging. Cold corporate environments or highly competitive fields drain their spirit.",
    financialHabits:
      "Cancer's approach to money is driven by the need for security. They are natural savers who build financial safety nets with discipline and foresight. Every dollar saved represents peace of mind and protection for their loved ones. Cancers are attracted to tangible investments — real estate, home improvements, and assets that create comfort and stability. They can be frugal to a fault when anxious and overly generous when feeling secure. Their challenge is balancing the desire to save with the need to enjoy the present moment.",
    spiritualTraits: [
      "Connects to the divine through emotion, intuition, and the heart",
      "Feels the sacred in the cycles of nature, especially the Moon and tides",
      "Finds spiritual nourishment in family traditions and ancestral wisdom",
      "Uses dreams and intuition as gateways to spiritual insight",
      "Believes that caring for others is a sacred act of service",
      "Draws spiritual strength from water — oceans, rivers, rain, and tears",
    ],
    luckyNumbers: [2, 7, 11, 16, 29],
    luckyColors: ["Silver", "White", "Pale Blue", "Sea Green"],
    luckyCrystals: ["Moonstone", "Pearl", "Ruby", "Selenite", "Clear Quartz"],
    luckyDays: ["Monday", "Thursday"],
  },

  leo: {
    sign: "leo",
    symbol: "♌",
    dateRange: "July 23 – August 22",
    element: "fire",
    quality: "fixed",
    rulingPlanet: "Sun",
    personality: [
      "Leo is the radiant heart of the zodiac — born to shine, lead, and inspire. Ruled by the Sun itself, Leos possess a natural magnetism and warmth that draws people into their orbit like planets around a star.",
      "Those born under this sign carry themselves with a regal confidence that is impossible to ignore. They have an innate sense of their own worth and an unapologetic desire to express their authentic selves.",
      "Leos are creative powerhouses with a flair for the dramatic. They approach life as a grand stage and themselves as the star of the show — not from vanity, but from an irrepressible need to express their brilliant inner light.",
      "Generosity is Leo's superpower. They love to uplift others, share their abundance, and celebrate the people around them. A Leo's praise is heartfelt, their encouragement is energizing, and their loyalty is absolute.",
      "At their core, Leos seek to create, love, and leave the world more vibrant than they found it. They are the kings and queens of the zodiac — not because they demand a throne, but because they can't help but reign.",
    ],
    strengths: [
      "Charismatic — natural magnetism that lights up every room",
      "Generous — gives freely of time, energy, resources, and affection",
      "Creative — boundless imagination and artistic self-expression",
      "Confident — unshakable self-assurance that inspires others",
      "Loyal — fiercely protective of friends, family, and loved ones",
      "Leadership — born to guide, motivate, and rally people together",
      "Optimistic — radiates positivity and sees the best in every situation",
    ],
    weaknesses: [
      "Arrogant — confidence can cross into domineering self-importance",
      "Dramatic — tendency toward theatrics and emotional exaggeration",
      "Stubborn — fixed fire is hard to redirect once set on a path",
      "Ego-driven — needs recognition and can struggle when overlooked",
      "Bossy — natural leadership can become controlling",
      "Extravagant — loves luxury and can overspend to maintain their image",
    ],
    loveStyle:
      "Leo loves with grand, cinematic passion. They are romantic, generous, and deeply devoted partners who want to sweep their loved one off their feet. For Leo, love is an adventure to be celebrated — expect grand gestures, heartfelt declarations, and unwavering support. They need a partner who appreciates their radiance and isn't threatened by their shine. A Leo's love language is affirmation and attention; they thrive on being admired and appreciated. In return, they offer a loyalty that is fierce and a generosity that knows no bounds. The ideal partner for Leo is someone who can stand proudly beside them as an equal, admiring their light while shining brightly themselves.",
    careerStyle:
    "Leo excels in careers that put them in the spotlight and allow creative self-expression. They thrive as performers, leaders, entrepreneurs, designers, educators, entertainers, and anyone in the public eye. Leos are born managers and executives who inspire teams through their vision and enthusiasm. They need work that offers visibility, recognition, and the opportunity to make an impact. Roles that keep them in the background or fail to appreciate their contributions will quickly lose a Leo's interest. They flourish when their work feels like a stage and their efforts are celebrated.",
    financialHabits:
      "Leo has a flair for earning and a taste for the finer things in life. They are confident earners who aren't afraid to invest in themselves — their image, their brand, their creative projects. Leos are generous spenders who love to treat themselves and others to luxurious experiences. Their financial challenge is balancing their love of splendor with practical long-term planning. Leos benefit from having a trusted financial partner who can help them build wealth while still allowing room for the grandeur they love. They are natural philanthropists who find joy in sharing their fortune.",
    spiritualTraits: [
      "Connects to the divine through creativity, joy, and self-expression",
      "Sees the sacred in the Sun, light, and the radiance of life",
      "Believes that honoring oneself is a spiritual practice",
      "Finds spiritual purpose in inspiring and uplifting others",
      "Uses creative arts as a form of meditation and worship",
      "Views life as a sacred performance — each act a gift to the world",
    ],
    luckyNumbers: [1, 4, 10, 19, 28],
    luckyColors: ["Gold", "Orange", "Purple", "Crimson"],
    luckyCrystals: ["Sunstone", "Ruby", "Carnelian", "Golden Topaz", "Amber"],
    luckyDays: ["Sunday", "Saturday"],
  },

  virgo: {
    sign: "virgo",
    symbol: "♍",
    dateRange: "August 23 – September 22",
    element: "earth",
    quality: "mutable",
    rulingPlanet: "Mercury",
    personality: [
      "Virgo is the analyst of the zodiac — meticulous, discerning, and devoted to the pursuit of perfection. Ruled by Mercury, their mind is a finely tuned instrument of logic, analysis, and precision.",
      "Those born under this sign possess an extraordinary eye for detail and a drive to improve everything they touch. They see not just what is, but what could be — and they have the patience to bridge that gap.",
      "Virgos are natural servants in the highest sense. Their gift is discerning exactly what is needed — whether it's a flaw in a system, an unmet need, or a way to make someone's life better — and quietly providing it.",
      "Their humility belies their brilliance. Virgos rarely boast about their capabilities, preferring to let their impeccable work speak for itself. They are the architects of excellence in every field they enter.",
      "Beneath their practical, analytical exterior lies a deeply caring soul. Virgo's precision is an expression of love — they pay attention to the details because they care about the outcome and the people it affects.",
    ],
    strengths: [
      "Analytical — sharp mind that dissects problems with surgical precision",
      "Detail-oriented — catches what everyone else misses",
      "Reliable — follows through with consistent, high-quality work",
      "Practical — finds grounded, effective solutions to complex problems",
      "Humble — lets results speak without needing the spotlight",
      "Helpful — genuine desire to serve and improve the lives of others",
      "Disciplined — remarkable self-control and dedication to routines",
    ],
    weaknesses: [
      "Perfectionist — nothing is ever quite good enough",
      "Overcritical — applies the same high standards to others as to themselves",
      "Anxious — overthinking can lead to worry and analysis paralysis",
      "Reserved — struggles to open up emotionally and show vulnerability",
      "Controlling — wants everything done a certain way (their way)",
      "Hypochondriac — heightened awareness of the body can lead to health anxiety",
    ],
    loveStyle:
      "Virgo expresses love through acts of service and thoughtful attention. They notice the small things — how you take your coffee, your favorite book, the exact way you like to be comforted after a hard day. For Virgo, love is in the details. They are deeply devoted partners who show their care through reliability, practical support, and quiet presence. Virgo needs a partner who appreciates their thoughtfulness and doesn't mistake their analytical nature for coldness. They can be shy in romance initially, but once they trust, they are warm, loyal, and unfailingly supportive. The ideal partner for Virgo is someone who values integrity, communicates openly, and appreciates the beauty of a well-cared-for love.",
    careerStyle:
      "Virgo excels in careers that demand precision, analysis, and service. They are the backbone of every industry they enter — the editors, analysts, healthcare workers, scientists, accountants, and quality assurance experts who ensure excellence. Their Methodical nature and sharp eye for detail make them invaluable in research, healthcare, data analysis, nutrition, writing, and any technical field requiring exacting standards. Virgo thrives in environments that value competence over politics and reward thoroughness. They make excellent managers who lead by example and care deeply about their team's well-being and growth.",
    financialHabits:
      "Virgo is the budgeting master of the zodiac. They approach money with meticulous planning, careful tracking, and a long-term perspective. Spreadsheets, budgets, and financial goals are second nature to them. Virgos are natural savers who prioritize financial security and rarely make impulsive purchases. They invest wisely, researching thoroughly before committing. Their challenge is finding the balance between prudent saving and enjoying their wealth — they can be so focused on security that they forget to reward themselves. Learning to spend on experiences and joy is part of Virgo's financial growth.",
    spiritualTraits: [
      "Finds spiritual connection through service, healing, and helping others",
      "Approaches spirituality with discernment and a desire for practical wisdom",
      "Seeks purity of mind, body, and spirit through discipline and healthy living",
      "Believes that sacredness is found in the details and the present moment",
      "Uses meditation and mindfulness practices that have clear, proven benefits",
      "Draws spiritual insight from nature, daily routines, and acts of kindness",
    ],
    luckyNumbers: [5, 7, 12, 18, 27],
    luckyColors: ["Navy Blue", "Forest Green", "White", "Beige"],
    luckyCrystals: ["Sapphire", "Jade", "Peridot", "Carnelian", "Amazonite"],
    luckyDays: ["Wednesday", "Friday"],
  },

  libra: {
    sign: "libra",
    symbol: "♎",
    dateRange: "September 23 – October 22",
    element: "air",
    quality: "cardinal",
    rulingPlanet: "Venus",
    personality: [
      "Libra is the diplomat of the zodiac — graceful, charming, and deeply committed to balance and harmony. Ruled by Venus, they are natural aesthetes with an innate sense of beauty and proportion.",
      "Those born under this sign are seekers of justice who cannot bear to see imbalance or unfairness. They are the mediators, the peacemakers, the ones who bring opposing sides together.",
      "Libras possess an extraordinary social intelligence. They know how to navigate complex social situations with tact, charm, and genuine warmth. People are naturally drawn to their graceful energy.",
      "Their greatest gift is their ability to see every side of a situation. This makes them fair and objective, but it can also lead to chronic indecisiveness.",
      "At their core, Libras crave partnership and connection. They thrive in relationships and are at their best when sharing their lives with someone they love.",
    ],
    strengths: [
      "Diplomatic — natural peacemaker who resolves conflict with grace",
      "Charming — magnetic personality that draws people in",
      "Fair-minded — unwavering commitment to justice and equality",
      "Social — thrives in collaborative and community settings",
      "Aesthetic — deep appreciation for beauty, art, and elegance",
      "Cooperative — excellent team player and collaborator",
      "Romantic — devoted and idealistic in love",
    ],
    weaknesses: [
      "Indecisive — struggles to commit to choices and opinions",
      "People-pleasing — prioritizes others' happiness over own needs",
      "Avoids conflict — can sweep issues under the rug instead of addressing them",
      "Superficial — may prioritize appearances over substance",
      "Resentful — avoids confrontation but harbors hidden resentment",
      "Easily influenced — too open to others' opinions at the expense of their own",
    ],
    loveStyle:
      "Libra is the ultimate romantic of the zodiac. They believe in true love, partnership, and happily-ever-after. Romance for Libra is about beauty, harmony, and shared experiences — candlelit dinners, long conversations, and elegant gestures of affection. They are devoted partners who thrive in committed relationships. Libra needs a partner who stimulates them intellectually, shares their appreciation for beauty and culture, and values partnership as much as they do. Conflict is deeply uncomfortable for Libra, so they need a partner who can address issues gently without creating drama. In return, Libra offers unwavering loyalty, charm, and a beautiful life built together.",
    careerStyle:
      "Libra excels in careers that involve diplomacy, aesthetics, and collaboration. They make excellent lawyers, judges, diplomats, designers, artists, counselors, and public relations professionals. Their natural sense of fairness and ability to see all sides makes them outstanding mediators. Libras thrive in beautiful, harmonious work environments with positive team dynamics. They struggle in hostile, competitive, or ugly work settings. Any role that allows them to create beauty, foster harmony, or advocate for justice is a perfect fit.",
    financialHabits:
      "Libra has an eye for quality and a love of beautiful things, which can make them inclined to spend on luxury, art, and aesthetic pleasures. They are generous gift-givers who enjoy sharing their good fortune with loved ones. While they appreciate financial balance, they can struggle with budgeting when tempted by beauty. Libras benefit from automated savings and working with a financial partner who provides accountability. Their financial strength lies in their ability to negotiate and create mutually beneficial arrangements.",
    spiritualTraits: [
      "Connects to the divine through beauty, art, and harmonious environments",
      "Finds spiritual meaning in relationships and partnership",
      "Seeks balance and harmony as a spiritual practice",
      "Believes justice and fairness are sacred principles",
      "Uses music, art, and creative expression as forms of meditation",
      "Draws spiritual insight from social connections and community",
    ],
    luckyNumbers: [6, 7, 11, 15, 24],
    luckyColors: ["Pink", "Light Blue", "Lavender", "White"],
    luckyCrystals: ["Opal", "Rose Quartz", "Lapis Lazuli", "Peridot", "Moonstone"],
    luckyDays: ["Friday", "Saturday"],
  },

  scorpio: {
    sign: "scorpio",
    symbol: "♏",
    dateRange: "October 23 – November 21",
    element: "water",
    quality: "fixed",
    rulingPlanet: "Pluto",
    personality: [
      "Scorpio is the intensity of the zodiac — passionate, mysterious, and magnetically powerful. Ruled by Pluto, they embody the forces of transformation, death, and rebirth.",
      "Those born under this sign possess an emotional depth that few can fathom. They feel everything with extraordinary intensity — love, pain, desire, and ambition all burn with an inner fire.",
      "Scorpios are natural detectives, drawn to uncover what is hidden beneath the surface. Nothing escapes their penetrating gaze, and they have an uncanny ability to sense when something is wrong.",
      "Their loyalty is fierce and absolute. Once a Scorpio commits to you, they will defend, protect, and stand by you through anything. But betray them, and their sting is unforgettable.",
      "Beneath their controlled exterior lies a volcano of emotion. Scorpios are masters of emotional discipline, but when they unleash their passion, it is transformative.",
    ],
    strengths: [
      "Passionate — brings intense depth to everything they do",
      "Resourceful — extraordinary ability to navigate crisis and emerge stronger",
      "Loyal — fiercely devoted to those who earn their trust",
      "Intuitive — almost psychic ability to read people and situations",
      "Determined — unstoppable when focused on a goal",
      "Transformative — exceptional capacity for personal growth and rebirth",
      "Brave — fearless in facing the dark and difficult",
    ],
    weaknesses: [
      "Jealous — possessive tendencies in relationships",
      "Secretive — guards their inner world too carefully",
      "Vengeful — never forgets a betrayal and seeks justice",
      "Distrusting — slow to trust and quick to suspect",
      "Obsessive — can fixate on people, goals, or grudges",
      "Controlling — needs to feel in command of every situation",
    ],
    loveStyle:
      "Scorpio loves with everything they have. There is no halfway for Scorpio — they dive into love with total commitment and passionate intensity. They seek a partner who can handle their emotional depth and match their intensity. Trust is everything; earning a Scorpio's trust takes time, but once given, it is unshakeable. They are fiercely protective, deeply sensual, and incredibly devoted partners. Betrayal is unforgivable. Scorpio needs a partner who is honest, transparent, and brave enough to explore the emotional depths with them. In return, they offer a love that is transformative, passionate, and absolutely unwavering.",
    careerStyle:
      "Scorpio excels in careers that require depth, investigation, and transformative impact. They thrive as detectives, psychologists, surgeons, researchers, investigative journalists, and crisis managers. Their ability to navigate the dark and uncover hidden truths makes them exceptional in any role that involves digging beneath the surface. Scorpios are natural leaders who command respect and inspire loyalty. They need work that feels meaningful and allows them to make a significant impact. Superficial or mundane work drains their spirit.",
    financialHabits:
      "Scorpio approaches finances with strategic intensity. They are natural investors who understand the power of compound growth and are willing to take calculated risks for substantial returns. Scorpios are excellent at building wealth through focused determination and are not afraid of the work required. They are private about their finances and value financial independence above all. Their challenge is avoiding obsession with wealth and learning to let go of financial control. Trusting a financial advisor can be difficult but necessary.",
    spiritualTraits: [
      "Connects to the divine through deep emotional and transformative experiences",
      "Draws spiritual power from facing shadows and embracing darkness",
      "Believes that transformation is the path to enlightenment",
      "Finds sacred meaning in the cycles of death and rebirth",
      "Uses intense meditation and deep introspection as spiritual practice",
      "Seeks spiritual truth beneath the surface of all things",
    ],
    luckyNumbers: [8, 11, 18, 22, 29],
    luckyColors: ["Black", "Deep Red", "Maroon", "Dark Purple"],
    luckyCrystals: ["Obsidian", "Garnet", "Malachite", "Bloodstone", "Smoky Quartz"],
    luckyDays: ["Tuesday", "Thursday"],
  },

  sagittarius: {
    sign: "sagittarius",
    symbol: "♐",
    dateRange: "November 22 – December 21",
    element: "fire",
    quality: "mutable",
    rulingPlanet: "Jupiter",
    personality: [
      "Sagittarius is the adventurer of the zodiac — optimistic, freedom-loving, and eternally in pursuit of truth and meaning. Ruled by Jupiter, the planet of expansion, they are driven to explore, learn, and grow.",
      "Those born under this sign possess an unquenchable thirst for adventure. Whether traveling the world, exploring new ideas, or seeking spiritual truth, Sagittarius is always on a quest for something greater.",
      "Their optimism is legendary. Sagittarians have an uncanny ability to find the silver lining in any situation and inspire others with their infectious enthusiasm for life.",
      "Honesty is their policy — sometimes to a fault. Sagittarians speak their truth with refreshing directness, though they can occasionally lack the tact that more sensitive souls require.",
      "At their core, Sagittarians are seekers of wisdom. They believe that life is a grand adventure meant to be lived fully, freely, and with an open heart.",
    ],
    strengths: [
      "Optimistic — sees possibilities where others see obstacles",
      "Adventurous — always ready for new experiences and exploration",
      "Honest — direct, truthful, and values authentic communication",
      "Independent — fiercely free-spirited and self-reliant",
      "Philosophical — seeks deep meaning and higher understanding",
      "Generous — shares knowledge, resources, and joy freely",
      "Enthusiastic — infectious energy that inspires those around them",
    ],
    weaknesses: [
      "Blunt — honesty can cross into insensitivity",
      "Restless — struggles with commitment and routine",
      "Impatient — wants results and adventures immediately",
      "Tactless — may speak without considering others' feelings",
      "Overconfident — optimism can lead to underestimating risks",
      "Commitment-phobic — freedom is so precious that settling down feels like confinement",
    ],
    loveStyle:
      "Sagittarius approaches love as a grand adventure. They seek a partner who shares their love of exploration, intellectual curiosity, and zest for life. For Sagittarius, love must never feel like a cage — they need a relationship that expands their world, not limits it. They are honest, warm, and enthusiastic partners who bring excitement and spontaneity to their relationships. The ideal partner is someone who can keep up with their restless spirit, engage in philosophical debates, and join them on their adventures. Routine and possessiveness are relationship killers for Sagittarius. They express love through shared experiences and intellectual connection.",
    careerStyle:
      "Sagittarius thrives in careers that offer freedom, variety, and the opportunity to explore. They excel as travelers, teachers, philosophers, writers, guides, entrepreneurs, and anyone in publishing or media. Sagittarians need work that feels meaningful and allows them to grow continuously. They are natural teachers who love sharing knowledge. They struggle in jobs that confine them to a desk, require repetitive tasks, or limit their freedom. Remote work, travel roles, and positions with flexibility are ideal.",
    financialHabits:
      "Sagittarius has a free-spirited approach to money — they can earn generously and spend impulsively, especially on travel, education, and experiences. Their optimism about the future can lead to financial risk-taking. Sagittarians benefit from financial systems that allow freedom while providing a safety net. Their greatest financial asset is their ability to generate income through multiple streams and their willingness to invest in growth. Their challenge is disciplined saving and resisting the temptation to overspend in pursuit of adventure.",
    spiritualTraits: [
      "Connects to the divine through exploration, travel, and expanding horizons",
      "Seeks spiritual truth across cultures, philosophies, and traditions",
      "Believes that the search for truth is itself a sacred journey",
      "Finds spiritual meaning in freedom, adventure, and new experiences",
      "Uses study, teaching, and philosophical inquiry as spiritual practices",
      "Draws wisdom from the collective knowledge of humanity",
    ],
    luckyNumbers: [3, 7, 9, 12, 21],
    luckyColors: ["Purple", "Blue", "Orange", "Gold"],
    luckyCrystals: ["Turquoise", "Amethyst", "Lapis Lazuli", "Sodalite", "Citrine"],
    luckyDays: ["Thursday", "Wednesday"],
  },

  capricorn: {
    sign: "capricorn",
    symbol: "♑",
    dateRange: "December 22 – January 19",
    element: "earth",
    quality: "cardinal",
    rulingPlanet: "Saturn",
    personality: [
      "Capricorn is the achiever of the zodiac — ambitious, disciplined, and driven by an unwavering commitment to excellence. Ruled by Saturn, they understand that lasting success is built through patience, hard work, and responsibility.",
      "Those born under this sign possess a remarkable maturity and self-discipline that sets them apart. They think long-term, plan carefully, and execute with precision. Capricorns are the architects of their own success.",
      "Their ambition is not mere vanity — it is a deep-seated need to build something meaningful and lasting. Capricorns want to leave their mark on the world and are willing to put in the decades of work required.",
      "Beneath their serious, reserved exterior lies a dry wit and a deeply caring heart. Capricorns may not wear their emotions on their sleeve, but their loyalty and devotion run deep.",
      "At their core, Capricorns are teachers and builders. They achieve greatness not just for themselves but to pave the way for those who follow.",
    ],
    strengths: [
      "Ambitious — driven to achieve meaningful, lasting success",
      "Disciplined — remarkable self-control and dedication to goals",
      "Responsible — takes obligations seriously and follows through",
      "Patient — willing to put in long-term effort for worthwhile goals",
      "Practical — brings grounded wisdom to every situation",
      "Loyal — steadfast and dependable in relationships",
      "Wise — possesses mature judgment and perspective",
    ],
    weaknesses: [
      "Pessimistic — can focus too much on worst-case scenarios",
      "Rigid — resistant to change and unproven approaches",
      "Workaholic — can prioritize work over relationships and health",
      "Reserved — struggles to express emotions and show vulnerability",
      "Status-conscious — can be overly concerned with reputation",
      "Controlling — wants to manage outcomes and can micromanage",
    ],
    loveStyle:
      "Capricorn approaches love with the same seriousness and commitment they bring to everything else. They are not interested in casual flings — they want a partner who will walk the long road with them. Trust is built slowly over time, and once given, Capricorn's loyalty is absolute. They express love through acts of service, provision, and steadfast presence. Grand romantic gestures are rare, but quiet, consistent devotion is their love language. Capricorn needs a partner who understands their drive and supports their ambitions while reminding them to enjoy life's simple pleasures.",
    careerStyle:
      "Capricorn is built for leadership and achievement. They excel as executives, managers, entrepreneurs, architects, engineers, lawyers, and in any role that rewards discipline and long-term thinking. Their methodical approach and ability to navigate complex systems make them invaluable in corporate and institutional settings. Capricorns thrive when they can see the tangible results of their efforts and are working toward clearly defined goals. They need structure, clear expectations, and the autonomy to execute their vision. They make exceptional mentors and leaders who lead by example.",
    financialHabits:
      "Capricorn is the master of long-term financial planning. They are disciplined savers, savvy investors, and patient builders of wealth. Capricorns understand the power of delayed gratification and are willing to make short-term sacrifices for long-term security. They are drawn to traditional investments like real estate, blue-chip stocks, and retirement accounts. Their challenge is learning to enjoy their wealth along the way rather than always deferring happiness for future security. Generosity with family and building a legacy are important to them.",
    spiritualTraits: [
      "Connects to the divine through discipline, service, and meaningful work",
      "Finds spiritual meaning in building lasting structures and legacies",
      "Believes that responsibility and service are sacred duties",
      "Seeks wisdom through patience, experience, and honoring tradition",
      "Uses structured meditation and consistent spiritual practice",
      "Draws spiritual strength from ancestral wisdom and time-tested traditions",
    ],
    luckyNumbers: [4, 8, 13, 22, 26],
    luckyColors: ["Dark Brown", "Navy", "Forest Green", "Gray"],
    luckyCrystals: ["Garnet", "Ruby", "Obsidian", "Onyx", "Black Tourmaline"],
    luckyDays: ["Saturday", "Tuesday"],
  },

  aquarius: {
    sign: "aquarius",
    symbol: "♒",
    dateRange: "January 20 – February 18",
    element: "air",
    quality: "fixed",
    rulingPlanet: "Uranus",
    personality: [
      "Aquarius is the visionary of the zodiac — innovative, unconventional, and driven by a deep desire to make the world a better place. Ruled by Uranus, they are agents of change and revolution.",
      "Those born under this sign see the world differently. They have a unique perspective that allows them to envision solutions and possibilities that others cannot imagine. Aquarians are the inventors and humanitarians of the zodiac.",
      "Their independence is fierce. Aquarians march to the beat of their own drum and refuse to conform to societal expectations. They value their freedom of thought above all else.",
      "Aquarians are deeply intellectual and love exploring big ideas. They are drawn to conversations about the future, technology, social change, and the improvement of the human condition.",
      "Behind their sometimes-detached exterior is a heart that cares deeply about humanity. Aquarians may struggle with personal intimacy, but their love for the collective is boundless.",
    ],
    strengths: [
      "Visionary — sees future possibilities and innovative solutions",
      "Progressive — embraces change and forward-thinking ideas",
      "Independent — thinks freely and refuses to conform",
      "Intellectual — sharp mind fascinated by big ideas",
      "Humanitarian — genuine desire to improve the world for everyone",
      "Inventive — creative problem-solving with a unique perspective",
      "Open-minded — accepts and celebrates diversity in all forms",
    ],
    weaknesses: [
      "Detached — can be emotionally aloof and distant in relationships",
      "Unpredictable — erratic behavior can confuse loved ones",
      "Rebellious — resists authority even when compliance is wise",
      "Intellectually arrogant — can dismiss emotions as irrational",
      "Impractical — big ideas may lack grounding in reality",
      "Inconsistent — moods and interests shift unpredictably",
    ],
    loveStyle:
      "Aquarius approaches love with intellectual curiosity and a need for freedom. They are not traditional romantics — they seek a partner who is also a friend, an intellectual companion, and a fellow visionary. Emotional intensity and possessiveness repel them. Aquarius needs space to be themselves and will give the same freedom to their partner. They express love through shared ideas, intellectual stimulation, and loyalty to the relationship's higher purpose. The ideal partner is someone who respects their independence, engages their mind, and shares their vision for a better world.",
    careerStyle:
      "Aquarius excels in careers that involve innovation, technology, and social progress. They thrive as scientists, inventors, engineers, social activists, community organizers, and in any field that pushes boundaries. Their ability to think outside the box makes them exceptional in research, technology development, and creative problem-solving. Aquarians need work that feels meaningful and contributes to the greater good. They struggle in rigid, hierarchical environments that stifle their creativity. They are natural collaborators who bring diverse people together for a common cause.",
    financialHabits:
      "Aquarius has an unconventional approach to finances. They value freedom and experiences over material possessions and may prioritize funding their passions over building traditional wealth. Their spending can be erratic, driven by their latest visionary interest rather than a budget. Aquarians benefit from automated financial systems that keep them on track without requiring constant attention. Their financial strength lies in their innovative ability to generate income through unconventional means. Their challenge is maintaining consistency and building long-term financial security.",
    spiritualTraits: [
      "Connects to the divine through universal love and humanitarian service",
      "Finds spiritual meaning in collective progress and social evolution",
      "Believes that all beings are interconnected in a cosmic web of consciousness",
      "Seeks spiritual truth through science, technology, and rational inquiry",
      "Uses meditation on the collective good as a spiritual practice",
      "Draws inspiration from visionary thinkers and spiritual pioneers",
    ],
    luckyNumbers: [4, 7, 11, 17, 22],
    luckyColors: ["Electric Blue", "Turquoise", "Silver", "Purple"],
    luckyCrystals: ["Amethyst", "Aquamarine", "Labradorite", "Clear Quartz", "Angelite"],
    luckyDays: ["Saturday", "Wednesday"],
  },

  pisces: {
    sign: "pisces",
    symbol: "♓",
    dateRange: "February 19 – March 20",
    element: "water",
    quality: "mutable",
    rulingPlanet: "Neptune",
    personality: [
      "Pisces is the mystic of the zodiac — dreamy, compassionate, and deeply connected to the unseen realms. Ruled by Neptune, they are the visionaries, artists, and spiritual seekers who bridge the material and spiritual worlds.",
      "Those born under this sign possess an extraordinary capacity for empathy. They feel the emotions of others as if they were their own, making them deeply compassionate but also profoundly vulnerable.",
      "Pisceans live in a rich inner world of imagination, dreams, and creativity. Their artistic gifts are often extraordinary, channeling beauty and truth from realms that others cannot perceive.",
      "Their intuition is almost supernatural. Pisces has a direct line to the collective unconscious and can sense things that defy rational explanation. Their guidance is often wise beyond their years.",
      "At their core, Pisceans long for transcendence. They seek to dissolve the boundaries that separate and return to the ocean of universal love from which they came.",
    ],
    strengths: [
      "Compassionate — boundless empathy for all living beings",
      "Intuitive — possesses profound spiritual and emotional insight",
      "Creative — extraordinary artistic and imaginative gifts",
      "Adaptable — flows with life's changes with grace and resilience",
      "Selfless — gives generously without expecting return",
      "Dreamy — rich inner world of vision and imagination",
      "Spiritual — naturally attuned to higher dimensions of being",
    ],
    weaknesses: [
      "Escapist — retreats into fantasy when reality is painful",
      "Overly trusting — can be naive and easily taken advantage of",
      "Vague — struggles with boundaries, clarity, and practicality",
      "Victim mentality — can slip into martyrdom and helplessness",
      "Addiction-prone — susceptible to substance and behavioral escapes",
      "Overwhelmed — porous boundaries lead to emotional overload",
    ],
    loveStyle:
      "Pisces loves with transcendent, unconditional devotion. They seek a soulmate connection — a love that feels destined, spiritual, and beyond ordinary understanding. For Pisces, love is a merging of souls, a return to wholeness. They are the most romantic and idealistic partners in the zodiac, capable of profound devotion and selfless care. However, they need a partner who provides grounding and stability, as Pisces can easily lose themselves in love. They express love through emotional attunement, creative gestures, and spiritual connection. The ideal partner is someone who honors their sensitivity while providing the practical grounding they need.",
    careerStyle:
      "Pisces thrives in careers that allow creative expression, emotional connection, and spiritual exploration. They excel as artists, musicians, writers, healers, therapists, photographers, and in any role that serves others with compassion. Pisceans are drawn to helping professions where their empathy can make a real difference. They need work that feels meaningful and allows for creative and emotional expression. They struggle in cold corporate environments, highly competitive fields, or roles that require rigid structure. Their natural gifts are best expressed in flexible, creative, and compassionate settings.",
    financialHabits:
      "Pisces has a fluid relationship with money — it comes and goes with the tides of life. They are generous to a fault, often giving away more than they can afford. Budgeting and financial planning feel restrictive to their free-flowing nature. Pisces benefits from having a trusted partner or advisor who can provide financial structure. Their financial strength is their trust in the universe's abundance. Their challenge is grounding that trust in practical financial habits. Automating savings and using visual financial tracking can help.",
    spiritualTraits: [
      "Naturally attuned to the spiritual dimensions and unseen realms",
      "Connects to the divine through art, music, and creative expression",
      "Believes that all life is one and separation is an illusion",
      "Finds sacred meaning in dreams, visions, and intuitive insights",
      "Uses music, poetry, and creative visualization as spiritual practice",
      "Draws spiritual wisdom from the ocean of collective consciousness",
    ],
    luckyNumbers: [3, 7, 9, 12, 24],
    luckyColors: ["Sea Green", "Lavender", "White", "Silver"],
    luckyCrystals: ["Amethyst", "Moonstone", "Aquamarine", "Rose Quartz", "Lepidolite"],
    luckyDays: ["Thursday", "Monday"],
  },
};
